import { useState } from 'react';
import { CheckCircle, GraduationCap, RotateCcw, XCircle } from 'lucide-react';
import GlossaryText from '../components/GlossaryText';

const questions = [
  { area: 'Netzwerk', question: 'Ein /27-Netz soll geplant werden. Wie viele nutzbare Hostadressen stehen zur Verfügung?', options: ['30', '32', '62', '14'], answer: '30', explanation: '32-27=5 Hostbits. 2^5=32 Adressen, abzüglich Netz- und Broadcast-Adresse bleiben 30.' },
  { area: 'Datenschutz', question: 'Welcher Grundsatz verlangt, nur die für einen Zweck erforderlichen personenbezogenen Daten zu verarbeiten?', options: ['Datenminimierung', 'Hochverfügbarkeit', 'Redundanz', 'Caching'], answer: 'Datenminimierung', explanation: 'Die DSGVO fordert zweckgebundene und auf das erforderliche Maß beschränkte Verarbeitung.' },
  { area: 'Wirtschaftlichkeit', question: 'Welche Kennzahl vergleicht den Nutzen einer Investition mit ihren Kosten?', options: ['ROI', 'RPO', 'TTL', 'MTU'], answer: 'ROI', explanation: 'Return on Investment bewertet den wirtschaftlichen Rückfluss relativ zum eingesetzten Kapital.' },
  { area: 'Projekt', question: 'Was beschreibt ein Meilenstein im Projekt?', options: ['Ein wichtiges überprüfbares Ereignis ohne eigene Dauer', 'Jede einzelne Arbeitsminute', 'Nur das Projektbudget', 'Eine technische Störung'], answer: 'Ein wichtiges überprüfbares Ereignis ohne eigene Dauer', explanation: 'Meilensteine markieren zentrale Ergebnisse oder Entscheidungen im Projektverlauf.' },
  { area: 'Backup', question: 'Ein RPO von vier Stunden bedeutet was?', options: ['Höchstens vier Stunden Datenverlust sind akzeptabel', 'Der Restore darf vier Stunden dauern', 'Vier Backups pro Jahr', 'Vier Server sind erforderlich'], answer: 'Höchstens vier Stunden Datenverlust sind akzeptabel', explanation: 'Das RPO beschreibt den maximal akzeptierten Datenverlust als Zeitraum.' },
  { area: 'Berechtigungen', question: 'Warum werden Rechte bevorzugt Gruppen statt einzelnen Benutzern zugewiesen?', options: ['Bessere Wartbarkeit und Nachvollziehbarkeit', 'Weil Benutzer keine Rechte erhalten können', 'Weil Gruppen Passwörter ersetzen', 'Damit Backups schneller sind'], answer: 'Bessere Wartbarkeit und Nachvollziehbarkeit', explanation: 'Rollen- und gruppenbasierte Rechte reduzieren Einzelzuweisungen und vereinfachen Audits.' },
  { area: 'SQL', question: 'Welche Maßnahme schützt Anwendungscode am zuverlässigsten vor SQL-Injection?', options: ['Parametrisierte Abfragen', 'Stringverkettung', 'Längere Tabellennamen', 'Fehlermeldungen ausblenden'], answer: 'Parametrisierte Abfragen', explanation: 'Parameter trennen Daten von ausführbarem SQL-Code.' },
  { area: 'Change', question: 'Was muss vor einer riskanten produktiven Änderung vorhanden sein?', options: ['Test-, Kommunikations- und Rollbackplan', 'Nur die Zustimmung eines Kollegen', 'Ein deaktiviertes Monitoring', 'Gelöschte Logs'], answer: 'Test-, Kommunikations- und Rollbackplan', explanation: 'Ein kontrollierter Change benötigt Validierung, Kommunikation und einen belastbaren Rückweg.' },
];

export default function IhkPrep() {
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState(null);
  const [result, setResult] = useState(null);
  const [correct, setCorrect] = useState(0);
  if (index >= questions.length) return <div className="flex flex-col items-center gap-4 py-10 text-center"><GraduationCap size={58} className="text-[#00ff66]" /><h2 className="text-xl font-bold text-white">IHK-Runde abgeschlossen</h2><p className="text-sm text-[#c9d1d9]">{correct} von {questions.length} Aufgaben richtig.</p><button onClick={() => { setIndex(0); setCorrect(0); setSelected(null); setResult(null); }} className="cyber-btn"><RotateCcw size={15} className="mr-2" />neue Runde</button></div>;
  const item = questions[index];
  function check() { const ok = selected === item.answer; setResult(ok); if (ok) setCorrect((value) => value + 1); }
  function next() { setIndex((value) => value + 1); setSelected(null); setResult(null); }
  return <div className="flex flex-col gap-4 py-2"><div className="cyber-card p-4"><div className="flex items-center gap-2 text-[#00f0ff]"><GraduationCap size={20} /><h2 className="font-bold">IHK-Prüfungsvorbereitung</h2></div><p className="text-xs text-[#8b949e] mt-2">Technik, Datenschutz, Wirtschaftlichkeit und Projektarbeit in prüfungsnaher Sprache.</p></div><div className="cyber-card p-4"><div className="flex justify-between text-xs text-[#8b949e]"><span>{item.area}</span><span>{index + 1}/{questions.length}</span></div><GlossaryText as="h3" className="font-bold text-white mt-3 mb-4">{item.question}</GlossaryText><div className="flex flex-col gap-2">{item.options.map((option) => <button key={option} disabled={result !== null} onClick={() => setSelected(option)} className={`p-3 text-left rounded border text-sm ${selected === option ? 'border-[#00ff66] text-[#00ff66]' : 'border-[#30363d] text-[#c9d1d9]'}`}><GlossaryText>{option}</GlossaryText></button>)}</div>{result !== null && <div className={`mt-4 p-3 rounded border ${result ? 'border-[#00ff66]' : 'border-[#ff3355]'}`}><div className={`flex items-center gap-2 ${result ? 'text-[#00ff66]' : 'text-[#ff3355]'}`}>{result ? <CheckCircle size={17} /> : <XCircle size={17} />}{result ? 'richtig' : `Richtig: ${item.answer}`}</div><GlossaryText as="p" className="text-sm text-[#c9d1d9] mt-2">{item.explanation}</GlossaryText></div>}{result === null ? <button onClick={check} disabled={!selected} className="cyber-btn w-full mt-4">prüfen</button> : <button onClick={next} className="cyber-btn w-full mt-4">weiter</button>}</div></div>;
}
