import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { CheckCircle, AlertTriangle, Target, XCircle } from 'lucide-react';

export default function PatchCenter() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [training, setTraining] = useState([]); const [active, setActive] = useState(0); const [selected, setSelected] = useState(null); const [result, setResult] = useState(null);
  function load() { setLoading(true); api('/api/patch').then(setItems).finally(() => setLoading(false)); }
  useEffect(() => load(), []);
  async function startTraining() { const questions = await api('/api/patch/training'); setTraining(questions); setActive(0); setSelected(null); setResult(null); }
  async function retry() { const response = await api(`/api/patch/${training[active].patch_id}/retry`, { method: 'POST', body: JSON.stringify({ answer: selected }) }); setResult(response); }
  const unresolved = items.filter((item) => !item.resolved); const resolved = items.filter((item) => item.resolved);
  if (loading) return <div className="text-[#00ff66] py-10 text-center">schwachstellen-log wird geladen...</div>;
  if (training.length) { const item = training[active]; return <div className="flex flex-col gap-4 py-2"><div className="cyber-card p-4"><h2 className="font-bold text-[#ffcc00]">schwächen-training {active + 1}/{training.length}</h2><p className="mt-3 text-white">{item.question}</p></div><div className="flex flex-col gap-2">{item.options.map((option) => <button key={option} disabled={Boolean(result)} onClick={() => setSelected(option)} className={`rounded-lg border p-3 text-left text-sm ${selected === option ? 'border-[#00ff66] text-[#00ff66]' : 'border-[#30363d] text-[#c9d1d9]'}`}>{option}</button>)}</div>{result && <div className={`cyber-card p-3 text-sm ${result.correct ? 'text-[#00ff66]' : 'text-[#ff3355]'}`}>{result.correct ? <CheckCircle className="mr-2 inline" size={17} /> : <XCircle className="mr-2 inline" size={17} />}{result.correct ? 'Schwäche gepatcht.' : `Noch nicht richtig. Lösung: ${result.answer}`}<p className="mt-2 text-[#c9d1d9]">{result.explanation}</p></div>} {!result ? <button disabled={!selected} onClick={retry} className="cyber-btn">antwort prüfen</button> : <button onClick={() => { if (active + 1 < training.length) { setActive(active + 1); setSelected(null); setResult(null); } else { setTraining([]); load(); } }} className="cyber-btn">weiter</button>}<button onClick={() => setTraining([])} className="cyber-btn-outline">training beenden</button></div>; }
  return <div className="flex flex-col gap-4 py-2"><div className="cyber-card p-4"><h2 className="text-lg font-bold text-[#ff3355]">&gt; patch center</h2><p className="mt-1 text-xs text-[#8b949e]">Falsch beantwortete Fragen priorisiert wiederholen.</p></div>{unresolved.length > 0 && <button onClick={startTraining} className="cyber-btn"><Target size={17} className="mr-2" />schwächen-training starten ({unresolved.length})</button>}{unresolved.length === 0 && resolved.length === 0 && <div className="py-8 text-center text-[#8b949e]">Log sauber. Keine Schwachstellen erkannt.</div>}{unresolved.map((item) => <div key={item.id} className="cyber-card border-l-4 border-[#ff3355] p-4"><div className="text-[10px] uppercase tracking-widest text-[#8b949e]">{item.module_title}</div><div className="mt-1 text-sm font-bold text-white">{item.question}</div><div className="mt-2 flex gap-2 text-sm text-[#ffcc00]"><AlertTriangle size={18} />{item.diagnostic}</div></div>)}{resolved.map((item) => <div key={item.id} className="cyber-card p-4 opacity-60"><div className="text-sm text-[#00ff66]"><CheckCircle size={16} className="mr-2 inline" />{item.question}</div></div>)}</div>;
}
