export const BASICS_BEATS = [
  { type: 'say', text: 'Fangen wir ganz vorne an: Ein Netzwerk besteht hier aus mehreren eigenständigen Computern, die so verbunden sind, dass sie Informationen austauschen können. Das Internet ist ein Netzwerkverbund, aber nicht jedes Netzwerk ist automatisch das Internet.', visual: 'network' },
  { type: 'say', text: 'Vernetzung hat drei zentrale Ziele: Ressourcen und Informationen gemeinsam nutzen, auch über Entfernungen schnell große Datenmengen austauschen und bereitgestellte Dienste verwenden.', endOfSection: true },
  { type: 'question', prompt: 'Welche Aussage beschreibt ein Netzwerk im Lehrgangskontext am besten?', options: ['Mehrere verbundene Computer tauschen Informationen aus und nutzen Ressourcen oder Dienste gemeinsam.', 'Nur Computer mit direktem Internetzugang bilden ein Netzwerk.', 'Ein einzelner Computer mit mehreren Programmen ist bereits ein Netzwerk.'], correct: 0, explanation: 'Ein Netzwerk verbindet mehrere eigenständige Computer zum Informationsaustausch. Ein Internetzugang ist dafür nicht erforderlich.' },
  { type: 'say', text: 'Ein Dienst ist eine bereitgestellte Funktionalität oder Leistung. Netzwerkdienste stellen Teilnehmern zum Beispiel Speicher, Mail, Zeit, Web, einen Verzeichnisdienst oder die IP-Adressvergabe bereit. Auch der Windows-Aufgabenplaner und die Druckerwarteschlange sind Beispiele für Systemdienste.', endOfSection: true },
  { type: 'question', prompt: 'Was beschreibt einen Dienst am besten?', options: ['Regeln für die Kommunikation', 'Eine bereitgestellte Funktion oder Leistung', 'Eine feste Verbindung zwischen Vermittlungsstellen'], correct: 1, explanation: 'Ein Dienst beschreibt eine angebotene Funktionalität. Wie darüber kommuniziert wird, regeln Protokolle.' },
  { type: 'say', text: 'Ein Protokoll legt gemeinsame Regeln für Sender und Empfänger fest. Diese Regeln können Reihenfolge, Inhalt und Darstellung von Nachrichten sowie die Fehlerüberprüfung betreffen. Beispiele sind ARP, IPv4, ICMP, TCP, UDP, HTTP, FTP, SMB und IMAP.' },
  { type: 'say', text: 'Als Lernhilfe kannst du fragen: WAS wird angeboten? Das ist der Dienst. Nach welchen REGELN wird kommuniziert? Das beschreibt ein Protokoll. Web ist eine angebotene Funktion; HTTP kann dafür als Protokoll verwendet werden.', visual: 'service-protocol', endOfSection: true },
  { type: 'question', prompt: 'Welche Zuordnung trennt Dienst und Protokoll korrekt?', options: ['Web = Dienst, HTTP = Protokoll', 'HTTP = Dienst, Web = Protokoll', 'Web und HTTP sind immer genau dasselbe'], correct: 0, explanation: 'Web bezeichnet die angebotene Funktion. HTTP legt Kommunikationsregeln fest, die in diesem Kontext verwendet werden können.' },
  { type: 'say', text: 'Bei leitungsvermittelter Kommunikation wird vorab eine feste Verbindung über die beteiligten Vermittlungsstellen aufgebaut und während der Übertragung aufrechterhalten. Der Lehrgang nennt als Vorteil eine meist konstante Bandbreite; klassische Telefonie vor der IP-Telefonie ist ein Beispiel.' },
  { type: 'say', text: 'Bei paketvermittelter Kommunikation werden Nutzdaten in Paketen übertragen. Vermittlungsstellen beziehungsweise Router bestimmen den weiteren Weg. Alternative Wege können genutzt und ausgefallene oder überlastete Strecken umgangen werden. Dabei muss nicht jedes Paket einen anderen Weg nehmen.', endOfSection: true },
  { type: 'question', prompt: 'Was kennzeichnet paketvermittelte Kommunikation?', options: ['Vorab wird für die gesamte Dauer zwingend eine feste Leitung reserviert.', 'Daten werden als Pakete übertragen und Vermittlungsstellen bestimmen den weiteren Weg.', 'Jedes Paket muss einen anderen Weg als das vorherige nehmen.'], correct: 1, explanation: 'Router beziehungsweise Vermittlungsstellen leiten Pakete weiter. Alternative Wege sind möglich, aber nicht für jedes Paket vorgeschrieben.' },
  { type: 'say', text: 'Eine andere Frage ist das Verbindungsverhalten: Verbindungsorientiert bedeutet, dass vor den eigentlichen Nutzdaten eine Verbindung beziehungsweise ein Kommunikationszustand aufgebaut wird. TCP ist das Lehrgangsbeispiel.' },
  { type: 'say', text: 'Verbindungslos bedeutet, dass ohne einen vergleichbaren vorherigen Verbindungsaufbau gesendet wird. UDP ist das Lehrgangsbeispiel. Das bedeutet nicht, dass grundsätzlich keinerlei Steuerinformationen existieren.', endOfSection: true },
  { type: 'question', prompt: 'Welche Aussage zum Verbindungsverhalten ist richtig?', options: ['TCP ist das Lehrgangsbeispiel für verbindungsorientierte Kommunikation.', 'UDP baut vor Nutzdaten immer einen vergleichbaren Kommunikationszustand wie TCP auf.', 'Verbindungslos bedeutet ausnahmslos ohne jede Steuerinformation.'], correct: 0, explanation: 'TCP dient hier als Beispiel für verbindungsorientiertes, UDP für verbindungsloses Verhalten. Die Aussage über keinerlei Steuerinformationen wäre zu absolut.' },
  { type: 'say', text: 'Jetzt die entscheidende Trennung: Leitungs- oder Paketvermittlung beschreibt die Vermittlungsart. Verbindungsorientiert oder verbindungslos beschreibt das Verbindungsverhalten. Das sind zwei unterschiedliche Kommunikationsachsen.', visual: 'communication-axes' },
  { type: 'say', text: 'Paketvermittelte Kommunikation kann verbindungsorientiert oder verbindungslos stattfinden. Paketvermittelt bedeutet deshalb nicht automatisch verbindungslos.', endOfSection: true },
  { type: 'question', prompt: 'Ein Netzwerk arbeitet paketvermittelt. Muss die Kommunikation deshalb verbindungslos sein?', options: ['Ja, paketvermittelt und verbindungslos sind gleichbedeutend.', 'Nein, Vermittlungsart und Verbindungsverhalten sind unterschiedliche Eigenschaften.', 'Ja, denn Pakete können niemals verbindungsorientiert übertragen werden.'], correct: 1, explanation: 'Paketvermittlung beschreibt den Weg der Daten. Verbindungsorientiert oder verbindungslos beschreibt dagegen das Kommunikationsverhalten. Beide Eigenschaften sind kombinierbar.' },
  { type: 'say', text: 'Die Begriffe Simplex, Halbduplex und Duplex werden in der aktuellen Lehrgangsquelle genannt. Ihre vollständige Erklärung gehört nicht in diesen Stand der Grundbegriffe-Lektion und wird erst mit gesicherter Lehrgangstheorie vertieft.', endOfSection: true },
  { type: 'question', prompt: 'Welche Aussage trennt die bisher behandelten Kategorien korrekt?', options: ['Leitungsvermittelt und paketvermittelt sind Vermittlungsarten.', 'Verbindungsorientiert und verbindungslos sind Vermittlungsarten.', 'Simplex beweist automatisch, dass ein Netzwerk paketvermittelt arbeitet.'], correct: 0, explanation: 'Leitungs- und Paketvermittlung beschreiben die Vermittlungsart. Das Verbindungsverhalten ist eine davon getrennte Achse.' },
];

export const BASICS_PRACTICE_QUESTIONS = [
  { facet: 'network', question: 'Was ist kein notwendiges Merkmal eines Netzwerks?', options: ['Mehrere eigenständige Computer', 'Möglichkeit zum Informationsaustausch', 'Ein Zugang zum öffentlichen Internet'], correct: 2, explanation: 'Ein lokales Netzwerk kann ohne Internetzugang bestehen.' },
  { facet: 'goals', question: 'Welches Ziel gehört zur Vernetzung?', options: ['Ressourcen und Informationen gemeinsam nutzen', 'Jeden Computer vollständig von anderen isolieren', 'Protokolle durch physische Leitungen ersetzen'], correct: 0, explanation: 'Gemeinsame Ressourcen, schneller Datenaustausch und bereitgestellte Dienste sind zentrale Ziele.' },
  { facet: 'service-protocol', question: 'Welche Reihe enthält nur Protokolle?', options: ['HTTP, TCP, SMB', 'Web, Mail, Speicher', 'Druckerwarteschlange, IMAP, Zeit'], correct: 0, explanation: 'HTTP, TCP und SMB definieren Kommunikationsregeln. Web, Mail, Speicher, Zeit und Druckerwarteschlange bezeichnen Funktionen oder Dienste.' },
  { facet: 'service-protocol', question: 'Ein Server bietet zentralen Speicher an. Was beschreibt „Speicher“ hier?', options: ['Einen Dienst', 'Ein Protokoll', 'Eine Vermittlungsart'], correct: 0, explanation: 'Speicher ist die bereitgestellte Funktion. Ein verwendetes Protokoll beschreibt getrennt davon die Kommunikationsregeln.' },
  { facet: 'protocol', question: 'Warum benötigen Kommunikationspartner ein gemeinsames Protokoll?', options: ['Damit Regeln für Nachrichten und Fehlerprüfung übereinstimmen', 'Damit jeder Sender beliebige Darstellungen ohne Abstimmung nutzt', 'Damit keine Vermittlungsstelle mehr erforderlich sein kann'], correct: 0, explanation: 'Gemeinsame Regeln sorgen dafür, dass Sender und Empfänger Nachrichten gleich verstehen und prüfen können.' },
  { facet: 'switching', question: 'Vor der Übertragung wird eine feste Verbindung aufgebaut und aufrechterhalten. Welche Vermittlungsart ist gemeint?', options: ['Leitungsvermittelt', 'Paketvermittelt', 'Verbindungslos'], correct: 0, explanation: 'Der feste Verbindungsweg gehört zur leitungsvermittelten Kommunikation.' },
  { facet: 'switching', question: 'Welche Aussage zur Paketvermittlung ist korrekt?', options: ['Router können den weiteren Weg der Pakete bestimmen.', 'Jedes Paket muss zwingend einen anderen Weg nehmen.', 'Vor jeder Übertragung wird eine feste Leitung für die gesamte Dauer reserviert.'], correct: 0, explanation: 'Alternative Wege sind möglich; ein anderer Weg für jedes Paket ist aber nicht vorgeschrieben.' },
  { facet: 'connection', question: 'Vor den Nutzdaten wird ein Kommunikationszustand aufgebaut. Wie heißt dieses Verhalten?', options: ['Verbindungsorientiert', 'Verbindungslos', 'Paketvermittelt'], correct: 0, explanation: 'Der vorherige Verbindungs- beziehungsweise Zustandsaufbau kennzeichnet verbindungsorientiertes Verhalten.' },
  { facet: 'connection', question: 'Welches Lehrgangsbeispiel steht für verbindungslose Kommunikation?', options: ['UDP', 'TCP', 'klassische Telefonie'], correct: 0, explanation: 'UDP ist das Lehrgangsbeispiel für verbindungsloses Verhalten.' },
  { facet: 'axes', question: 'Ein Kollege sagt: „Paketvermittelt bedeutet automatisch verbindungslos.“ Wie ordnest du das ein?', options: ['Falsch: Vermittlungsart und Verbindungsverhalten sind getrennte Achsen.', 'Richtig: Pakete schließen einen Verbindungszustand aus.', 'Richtig: Paketvermittlung verwendet immer UDP.'], correct: 0, explanation: 'Paketvermittelte Kommunikation kann verbindungsorientiert oder verbindungslos stattfinden.' },
];

export function pickDiverseBasicsQuestions(rng = Math.random) {
  const shuffled = [...BASICS_PRACTICE_QUESTIONS].sort(() => rng() - 0.5);
  const selected = ['service-protocol', 'axes'].map((facet) => shuffled.find((question) => question.facet === facet));
  const usedFacets = new Set(selected.map((question) => question.facet));
  for (const question of shuffled) {
    if (usedFacets.has(question.facet)) continue;
    selected.push(question);
    usedFacets.add(question.facet);
    if (selected.length === 5) return selected;
  }
  return selected;
}
