export const glossary = {
  'AD': { title: 'Active Directory (AD)', text: 'Microsoft-Verzeichnisdienst zur zentralen Verwaltung von Benutzern, Computern, Gruppen und Zugriffsrechten in einer Windows-Domäne.' },
  'Active Directory': { title: 'Active Directory', text: 'Microsoft-Verzeichnisdienst zur zentralen Verwaltung von Identitäten, Geräten, Gruppen und Richtlinien.' },
  'AGDLP': { title: 'AGDLP', text: 'Berechtigungsprinzip: Accounts kommen in globale Gruppen, diese in domänenlokale Gruppen, und diese erhalten Permissions (Berechtigungen).' },
  'APIPA': { title: 'Automatic Private IP Addressing (APIPA)', text: 'Windows vergibt automatisch eine Adresse aus 169.254.0.0/16, wenn kein DHCP-Server erreicht und keine statische Adresse verwendet wird.' },
  'CIDR': { title: 'Classless Inter-Domain Routing (CIDR)', text: 'Schreibweise wie /24, die angibt, wie viele Bits einer IP-Adresse den Netzwerkanteil bilden.' },
  'DHCP': { title: 'Dynamic Host Configuration Protocol (DHCP)', text: 'Netzwerkdienst, der Clients automatisch IP-Adresse, Subnetzmaske, Gateway und meist DNS-Server zuweist.' },
  'DNS': { title: 'Domain Name System (DNS)', text: 'Übersetzt Namen wie server.firma.local in IP-Adressen und stellt weitere Informationen über Netzwerkdienste bereit.' },
  'GPO': { title: 'Group Policy Object (GPO)', text: 'Gruppenrichtlinienobjekt, mit dem Windows-Einstellungen zentral auf Benutzer und Computer angewendet werden.' },
  'IP': { title: 'Internet Protocol (IP)', text: 'Protokoll zur logischen Adressierung und Weiterleitung von Datenpaketen zwischen Netzwerken.' },
  'IPv4': { title: 'Internet Protocol Version 4 (IPv4)', text: 'Weit verbreitete IP-Version mit 32-Bit-Adressen, zum Beispiel 192.168.1.10.' },
  'IPv6': { title: 'Internet Protocol Version 6 (IPv6)', text: 'Neuere IP-Version mit 128-Bit-Adressen und einem wesentlich größeren Adressraum.' },
  'LDAP': { title: 'Lightweight Directory Access Protocol (LDAP)', text: 'Protokoll zum Lesen und Verändern von Informationen in Verzeichnisdiensten wie Active Directory.' },
  'MFA': { title: 'Multi-Faktor-Authentifizierung (MFA)', text: 'Anmeldung mit mindestens zwei unterschiedlichen Faktoren, etwa Passwort und Authenticator-App.' },
  'NAT': { title: 'Network Address Translation (NAT)', text: 'Übersetzt Netzwerkadressen, häufig private interne Adressen in eine öffentliche Adresse für den Internetzugang.' },
  'NTFS': { title: 'New Technology File System (NTFS)', text: 'Windows-Dateisystem mit detaillierten Berechtigungen, Besitzinformationen, Verschlüsselung und weiteren Funktionen.' },
  'OSI': { title: 'Open Systems Interconnection (OSI)', text: 'Referenzmodell mit sieben Schichten zur Einordnung von Netzwerkfunktionen und zur strukturierten Fehlersuche.' },
  'RAID': { title: 'Redundant Array of Independent Disks (RAID)', text: 'Verbund mehrerer Datenträger für Verfügbarkeit oder Leistung. RAID ersetzt kein getrenntes Backup.' },
  'RPO': { title: 'Recovery Point Objective (RPO)', text: 'Maximal akzeptierter Datenverlust, als Zeitraum ausgedrückt. Beispiel: RPO 4 Stunden bedeutet höchstens vier Stunden Datenverlust.' },
  'RTO': { title: 'Recovery Time Objective (RTO)', text: 'Maximal akzeptierte Zeit, bis ein Dienst nach einem Ausfall wieder verfügbar sein muss.' },
  'SMB': { title: 'Server Message Block (SMB)', text: 'Netzwerkprotokoll für Windows-Datei- und Druckerfreigaben, üblicherweise über TCP-Port 445.' },
  'SOC': { title: 'Security Operations Center (SOC)', text: 'Team oder Bereich zur laufenden Überwachung, Erkennung und Bearbeitung von IT-Sicherheitsvorfällen.' },
  'SQL': { title: 'Structured Query Language (SQL)', text: 'Sprache zum Abfragen und Verändern relationaler Datenbanken.' },
  'SSH': { title: 'Secure Shell (SSH)', text: 'Verschlüsseltes Protokoll zur Fernadministration, normalerweise über TCP-Port 22.' },
  'TCP': { title: 'Transmission Control Protocol (TCP)', text: 'Verbindungsorientiertes Transportprotokoll mit zuverlässiger, geordneter Datenübertragung.' },
  'TLS': { title: 'Transport Layer Security (TLS)', text: 'Protokoll zur Verschlüsselung und Authentisierung von Netzwerkverbindungen, etwa bei HTTPS.' },
  'UDP': { title: 'User Datagram Protocol (UDP)', text: 'Verbindungsloses Transportprotokoll mit geringem Overhead, aber ohne garantierte Zustellung.' },
  'USV': { title: 'Unterbrechungsfreie Stromversorgung (USV)', text: 'Batteriegepufferte Stromversorgung, die kurze Ausfälle überbrückt und geordnetes Herunterfahren ermöglicht.' },
  'VLAN': { title: 'Virtual Local Area Network (VLAN)', text: 'Logische Trennung eines physischen Switch-Netzes in voneinander isolierte Broadcast-Domänen.' },
  'WinRM': { title: 'Windows Remote Management (WinRM)', text: 'Microsoft-Protokoll für entfernte Verwaltung, unter anderem als Grundlage von PowerShell Remoting.' },
  'A-Record': { title: 'DNS A-Record', text: 'DNS-Eintrag, der einen Hostnamen einer IPv4-Adresse zuordnet.' },
  'Baseline': { title: 'Baseline', text: 'Dokumentierter Normalzustand eines Systems. Abweichungen davon helfen, Störungen oder Angriffe zu erkennen.' },
  'Broadcast': { title: 'Broadcast-Adresse', text: 'Letzte Adresse eines IPv4-Subnetzes. Pakete an diese Adresse richten sich an alle Geräte im lokalen Subnetz.' },
  'Domain Controller': { title: 'Domain Controller', text: 'Server, der Active Directory bereitstellt und unter anderem Anmeldungen, Gruppen sowie Richtlinien verarbeitet.' },
  'Gateway': { title: 'Standard-Gateway', text: 'Routeradresse, an die ein Host Pakete für Ziele außerhalb seines eigenen Subnetzes sendet.' },
  'Idempotenz': { title: 'Idempotenz', text: 'Eigenschaft einer Automatisierung: Wiederholte Ausführung führt zuverlässig zum gleichen gewünschten Zustand.' },
  'Internet': { title: 'Internet', text: 'Weltweiter Verbund vieler unabhängiger Netzwerke. Geräte erreichen öffentliche Dienste über Router, Provider und standardisierte Internetprotokolle.' },
  'Intranet': { title: 'Intranet', text: 'Nicht öffentliches, internes Netzwerk einer Organisation. Es verwendet häufig dieselben Techniken wie das Internet, ist aber nur für berechtigte interne Nutzer erreichbar.' },
  'Fileserver': { title: 'Fileserver', text: 'Zentraler Server, der Dateien und Ordner für mehrere Benutzer über Netzwerkfreigaben bereitstellt und Zugriffsrechte kontrolliert.' },
  'ipconfig /renew': { title: 'ipconfig /renew', text: 'Windows-Befehl, der für Netzwerkadapter eine neue oder verlängerte IP-Konfiguration beim DHCP-Server anfordert.' },
  'Switchport': { title: 'Switchport', text: 'Physischer oder logischer Anschluss eines Netzwerk-Switches. Er kann unter anderem einem VLAN zugeordnet, aktiviert oder deaktiviert werden.' },
  'Switch': { title: 'Netzwerk-Switch', text: 'Verbindet Geräte innerhalb eines lokalen Netzwerks und leitet Ethernet-Frames anhand von MAC-Adressen an den passenden Port weiter.' },
  'Kerberos': { title: 'Kerberos', text: 'Ticketbasiertes Authentifizierungsprotokoll, das in Active Directory standardmäßig für Domänenanmeldungen verwendet wird.' },
  'Least Privilege': { title: 'Least Privilege', text: 'Sicherheitsprinzip: Benutzer und Dienste erhalten nur die Rechte, die sie für ihre Aufgabe tatsächlich benötigen.' },
  'Lease': { title: 'DHCP-Lease', text: 'Zeitlich begrenzte Zuweisung einer Netzwerkkonfiguration durch einen DHCP-Server an einen Client.' },
  'Link': { title: 'Netzwerk-Link', text: 'Aktive physische beziehungsweise direkte Verbindung zwischen Netzwerkschnittstelle und Gegenstelle, etwa einem Switch.' },
  'Rollback': { title: 'Rollback', text: 'Vorbereiteter Rückweg, mit dem eine fehlgeschlagene Änderung sicher auf den vorherigen Zustand zurückgesetzt wird.' },
  'Runbook': { title: 'Runbook', text: 'Dokumentierte, wiederholbare Schrittfolge für Diagnose, Betrieb oder Behebung eines bekannten Problems.' },
  'Subnetz': { title: 'Subnetz', text: 'Logisch abgegrenzter Teil eines IP-Netzes, definiert durch Netzwerkadresse und Subnetzmaske beziehungsweise CIDR-Präfix.' },
  'Token': { title: 'Sicherheitstoken', text: 'Enthält bei einer Windows-Anmeldung unter anderem Benutzer- und Gruppeninformationen, auf deren Basis Zugriffe geprüft werden.' },
};

export const glossaryTerms = Object.keys(glossary).sort((a, b) => b.length - a.length);
