// =============================================================================
// Knowledge Items – Active Directory Foundation
//
// Source: frontend/src/lib/academyLessons/adFoundation.js (planned)
// Primary references:
//   - Microsoft Learn: Active Directory Domain Services
//   - RFC 4511 (LDAP), RFC 4120 (Kerberos)
//   - Microsoft Windows Server DNS / Time Service documentation
//
// Course-specific simplifications are marked in item.sourceStatus.
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const AD_FOUNDATION_TOPIC_KEY = topicKey('active-directory-virtualbox', 'ad-foundation');

export const adFoundationKnowledgeItems = [
  {
    id: 'ad.directory.definition',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'directory-service',
    conceptCluster: 'ad.directory',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'ein Verzeichnisdienst',
      definition: 'Ein Verzeichnisdienst verwaltet Objekte und ihre Attribute an einer zentralen Stelle.',
      distractorDefinitions: [
        'Ein Dateiserver, der alle Unternehmensdaten speichert.',
        'Ein Routing-Protokoll für große Netze.',
        'Ein einzelner lokal gespeicherter Benutzerkonto-Manager.',
      ],
    },
    roleHints: ['technical', 'management'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.directory.object',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'directory-service',
    conceptCluster: 'ad.directory.object',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'ein Objekt im Verzeichnis',
      definition: 'Ein Objekt ist ein konkretes Verzeichnis-Element wie ein Benutzer, Computer, Drucker oder eine Gruppe.',
      distractorDefinitions: [
        'Eine einzelne Eigenschaft wie E-Mail oder Abteilung.',
        'Ein physisches Netzwerkkabel.',
        'Ein Typ von IP-Adresse.',
      ],
    },
    roleHints: ['support', 'technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.directory.attribute',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'directory-service',
    conceptCluster: 'ad.directory.attribute',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'ein Attribut',
      definition: 'Ein Attribut beschreibt eine Eigenschaft eines Verzeichnisobjekts, z. B. Name, E-Mail oder Abteilung.',
      distractorDefinitions: [
        'Das Objekt selbst, z. B. der Benutzer.',
        'Ein Protokoll zur Authentifizierung.',
        'Eine Netzwerk-Schnittstelle.',
      ],
    },
    roleHints: ['support', 'technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.directory.objectVsAttribute',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'directory-service',
    conceptCluster: 'ad.directory.objectVsAttribute',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'Unterscheidung zwischen Objekt und Attribut in einem Verzeichnis.',
      items: [
        { name: 'Objekt', description: 'Das eigentliche Verzeichnis-Element, z. B. ein Benutzer oder Computer.' },
        { name: 'Attribut', description: 'Eine einzelne Eigenschaft dieses Objekts, z. B. E-Mail-Adresse.' },
        { name: 'Container', description: 'Ein logischer Rahmen, der Objekte gruppiert, aber nicht die Eigenschaften einzelner Objekte.' },
        { name: 'Schema', description: 'Ein Regelwerk, das festlegt, welche Objekttypen und Attribute erlaubt sind.' },
      ],
    },
    roleHints: ['support', 'technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.centralized.problem',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'local-management-problem',
    conceptCluster: 'ad.centralized.problem',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      subject: 'rein lokale Benutzerverwaltung',
      description: 'Bei rein lokaler Verwaltung hat jeder Rechner eigene Konten. Benutzer haben an anderen Arbeitsplätzen keine Identität, und der Verwaltungsaufwand steigt stark.',
      distractorDescriptions: [
        'Jeder Benutzer kann sich an jedem Rechner automatisch anmelden.',
        'Konten werden zentral verwaltet und übernommen.',
        'Es gibt keine Probleme mit Passwörtern.',
      ],
    },
    roleHints: ['support', 'management'],
    sourceStatus: 'course_specific',
  },
  {
    id: 'ad.adds.definition',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'ad-ds',
    conceptCluster: 'ad.adds',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'Active Directory Domain Services (AD DS)',
      definition: 'AD DS ist der Windows-Dienst für einen zentralen Verzeichnisdienst in einer Domäne.',
      distractorDefinitions: [
        'Ein Dateiserver-Dienst, der alle Unternehmensdaten hält.',
        'Ein E-Mail-Verteiler für IT-Sicherheitsmeldungen.',
        'Ein Tool zur manuellen Konfiguration jedes einzelnen PCs.',
      ],
    },
    roleHints: ['technical', 'management'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.adds.purpose',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'ad-ds',
    conceptCluster: 'ad.adds.purpose',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      subject: 'AD DS',
      description: 'AD DS bietet zentrale Identitäten, Computer- und Gruppenverwaltung, Authentifizierung, Autorisierung und Richtlinien.',
      distractorDescriptions: [
        'AD DS speichert alle Unternehmensdaten, inklusive Datenbanken und Dateien.',
        'AD DS ersetzt alle Router und Switches im Netzwerk.',
        'AD DS ist nur für Desktop-Hintergrundbilder zuständig.',
      ],
    },
    roleHints: ['technical', 'management'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.dns.role',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'ad-dns',
    conceptCluster: 'ad.dns.role',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      subject: 'DNS im Active-Directory-Kontext',
      description: 'DNS hilft AD-Clients, passende Domain Controller und Dienste im Netzwerk zu finden.',
      distractorDescriptions: [
        'DNS ersetzt die zentrale Benutzerverwaltung.',
        'DNS speichert alle Passwörter der Domäne.',
        'DNS ist nur für die Übersetzung von Webseiten-URLs zuständig.',
      ],
    },
    roleHints: ['technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.kerberos.purpose',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'kerberos',
    conceptCluster: 'ad.kerberos',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'Kerberos',
      definition: 'Kerberos ist ein Authentifizierungsprotokoll, das mit Tickets arbeitet und Single-Sign-On ermöglicht.',
      distractorDefinitions: [
        'Ein Antivirus-Programm für Domain Controller.',
        'Ein Dateisystem für Windows-Drucker.',
        'Das gleiche wie Active Directory selbst.',
      ],
    },
    roleHints: ['security', 'technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.time.dependency',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'time',
    conceptCluster: 'ad.time',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      subject: 'Zeitabgleich für Kerberos',
      description: 'Kerberos ist auf eine konsistente Uhrzeit zwischen Clients und Servern angewiesen. Große Abweichungen können Authentifizierungen verhindern.',
      distractorDescriptions: [
        'Zeitabgleich ist nur für Datumsanzeigen am Desktop relevant.',
        'Kerberos funktioniert auch bei beliebig großer Zeitdifferenz.',
        'SNTP ist die einzige zulässige Zeitquelle in jedem Netz.',
      ],
    },
    roleHints: ['security', 'technical'],
    sourceStatus: 'needs_confirmation',
  },
  {
    id: 'ad.ldap.purpose',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'ldap',
    conceptCluster: 'ad.ldap',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'LDAP',
      definition: 'LDAP ist ein Protokoll, mit dem man Verzeichnisinformationen abfragen und ändern kann.',
      distractorDefinitions: [
        'LDAP ist dasselbe wie Active Directory.',
        'LDAP dient ausschließlich dem Datenaustausch zwischen Switches.',
        'LDAP ist ein Routing-Protokoll.',
      ],
    },
    roleHints: ['technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.smbntfs.smb',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'smb-vs-ntfs',
    conceptCluster: 'ad.smbntfs.smb',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'SMB',
      definition: 'SMB ist ein Netzwerkprotokoll für den Zugriff auf Dateien, Drucker und Ressourcen.',
      distractorDefinitions: [
        'SMB ist ein lokales Dateisystem auf der Festplatte.',
        'SMB erteilt Rechte auf Dateisystemebene.',
        'SMB ist ein Protokoll für die direkte CPU-Kommunikation.',
      ],
    },
    roleHints: ['technical', 'support'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.smbntfs.ntfs',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'smb-vs-ntfs',
    conceptCluster: 'ad.smbntfs.ntfs',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'NTFS',
      definition: 'NTFS ist ein lokales Dateisystem mit Berechtigungen auf Datei- und Ordnerebene.',
      distractorDefinitions: [
        'NTFS ist ein Netzwerkprotokoll für Druckerfreigaben.',
        'NTFS wird für die DNS-Auflösung verwendet.',
        'NTFS ist ein Authentifizierungsprotokoll.',
      ],
    },
    roleHints: ['technical', 'support'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.smbntfs.compare',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'smb-vs-ntfs',
    conceptCluster: 'ad.smbntfs.compare',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'SMB und NTFS arbeiten auf unterschiedlichen Ebenen.',
      compareOn: 'scope',
      items: [
        { name: 'SMB', scope: 'Netzwerkprotokoll für Datei- und Ressourcenzugriff', purpose: 'Transport über das Netzwerk' },
        { name: 'NTFS', scope: 'Lokales Dateisystem mit Berechtigungen', purpose: 'Rechte auf dem Datenträger' },
        { name: 'LDAP', scope: 'Protokoll für Verzeichnisabfragen', purpose: 'Lesen und Ändern von Verzeichnisdaten' },
        { name: 'Kerberos', scope: 'Ticket-basierte Authentifizierung', purpose: 'Identitätsnachweis' },
      ],
    },
    roleHints: ['technical', 'support'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.replication.purpose',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'replication',
    conceptCluster: 'ad.replication',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'AD-Replikation',
      definition: 'AD-Replikation sorgt dafür, dass mehrere Domain Controller Verzeichnisinformationen konsistent miteinander abgleichen.',
      distractorDefinitions: [
        'Replikation kopiert jedes 15 Sekunden alle Daten erneut über das Netz.',
        'Replikation hat in AD keine Funktion, weil ein DC allein arbeitet.',
        'Replikation ist ein Verfahren zum Schutz vor Viren.',
      ],
    },
    roleHints: ['technical', 'management'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.authn.definition',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'authn-authz',
    conceptCluster: 'ad.authn',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'Authentifizierung',
      definition: 'Authentifizierung beantwortet die Frage: „Wer bist du?“',
      distractorDefinitions: [
        '„Was darfst du?"',
        '„Welche Dateien sollen kopiert werden?"',
        '„Welcher Port ist geöffnet?"',
      ],
    },
    roleHints: ['security', 'support'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.authz.definition',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'authn-authz',
    conceptCluster: 'ad.authz',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'Autorisierung',
      definition: 'Autorisierung beantwortet die Frage: „Was darfst du?"',
      distractorDefinitions: [
        '„Wer bist du?"',
        '„Wie lautet dein Passwort?"',
        '„Welcher DNS-Server ist erreichbar?"',
      ],
    },
    roleHints: ['security', 'support'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.authnVsAuthz.compare',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'authn-authz',
    conceptCluster: 'ad.authnVsAuthz',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'Authentifizierung und Autorisierung sind zwei getrennte Schritte.',
      items: [
        { name: 'Authentifizierung', description: 'Identität nachweisen: Wer bist du?' },
        { name: 'Autorisierung', description: 'Berechtigung prüfen: Was darfst du?' },
        { name: 'Identifizierung', description: 'Eine Person oder ein Objekt benennen oder zuordnen.' },
        { name: 'Verifikation', description: 'Eine Angabe oder einen Nachweis auf Richtigkeit prüfen.' },
      ],
    },
    roleHints: ['security', 'support', 'technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.capabilities.overview',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'capabilities',
    conceptCluster: 'ad.capabilities',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      subject: 'Active Directory',
      description: 'AD bietet Skalierbarkeit, Erweiterbarkeit, zentrale Verwaltung, Delegation, DNS-Integration, richtlinienbasierte Verwaltung, Authentifizierung, Autorisierung und Replikation.',
      distractorDescriptions: [
        'AD ersetzt Firewall, Router und Switches.',
        'AD speichert alle Dateien und Datenbanken zentral.',
        'AD erlaubt keine Erweiterung um weitere Domänen.',
      ],
    },
    roleHints: ['management', 'technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.ldap.vsDirectory',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'ldap',
    conceptCluster: 'ad.ldap.vsDirectory',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'LDAP und Active Directory sind nicht dasselbe.',
      items: [
        { name: 'Active Directory', description: 'Microsofts Verzeichnisdienst in Windows-Domänen.' },
        { name: 'LDAP', description: 'Protokoll zum Zugriff auf Verzeichnisinformationen.' },
        { name: 'Kerberos', description: 'Ticket-basiertes Authentifizierungsprotokoll.' },
        { name: 'DNS', description: 'System zur Namensauflösung und Dienstelokalisierung.' },
      ],
    },
    roleHints: ['technical'],
    sourceStatus: 'verified',
  },
  {
    id: 'ad.kerberos.tickets',
    topicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceTopicKey: AD_FOUNDATION_TOPIC_KEY,
    sourceSection: 'kerberos',
    conceptCluster: 'ad.kerberos.tickets',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      subject: 'Kerberos-Tickets',
      description: 'Kerberos stellt nach einer erfolgreichen Anmeldung Tickets aus, mit denen sich der Benutzer bei Diensten ausweisen kann, ohne das Passwort erneut einzugeben.',
      distractorDescriptions: [
        'Tickets ersetzen den DNS-Server.',
        'Tickets speichern alle Datei-Berechtigungen.',
        'Tickets werden nur einmal pro Jahr ausgestellt.',
      ],
    },
    roleHints: ['security', 'technical'],
    sourceStatus: 'verified',
  },
];
