// =============================================================================
// Knowledge Items – Cisco Troubleshooting
//
// Source: frontend/src/lib/academyLessons/ciscoTroubleshooting.js
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const CISCO_TROUBLESHOOTING_TOPIC_KEY = topicKey('cisco-packet-tracer', 'troubleshooting');

export const ciscoTroubleshootingKnowledgeItems = [
  {
    id: 'ciscoTroubleshooting.approach',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'troubleshooting.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      statement: 'Troubleshooting entscheidet anhand eines Symptoms, welcher show-Befehl die richtige Information am schnellsten liefert.',
      description: 'Statt wahllos Befehle einzugeben, wählt man gezielt den passenden Diagnosebefehl.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.commands',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'uebersicht-classic',
    conceptCluster: 'troubleshooting.fundamentals',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { command: 'show ip interface brief', purpose: 'Status und IP aller Interfaces - schneller Einstieg bei Verbindungsproblemen' },
        { command: 'show vlan brief', purpose: 'VLAN-Zuweisungen aller Ports' },
        { command: 'show interfaces trunk', purpose: 'Trunk-Ports und erlaubte VLANs' },
        { command: 'show interfaces status', purpose: 'Kompakter Portstatus, VLAN, Duplex, Geschwindigkeit' },
        { command: 'show interfaces switchport', purpose: 'Detail-Ansicht eines einzelnen Ports (Access/Trunk)' },
        { command: 'show ip route', purpose: 'Routing-Tabelle - fehlende Route zu entferntem Netz' },
        { command: 'show arp', purpose: 'MAC-zu-IP-Zuordnung im lokalen Netz' },
        { command: 'show mac address-table', purpose: 'An welchem Port eine MAC-Adresse gelernt wurde' },
        { command: 'show running-config', purpose: 'Gesamte aktive Konfiguration' },
      ],
      description: 'Jedes Symptom hat typischerweise einen ersten Diagnosebefehl.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.order',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'vorgehen-classic',
    conceptCluster: 'troubleshooting.fundamentals',
    type: KNOWLEDGE_TYPES.ORDER,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.ORDERING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      order: [
        { step: 'show ip interface brief', note: 'Ist die Schnittstelle up?' },
        { step: 'show vlan brief / show interfaces switchport', note: 'Ist der Port im richtigen VLAN?' },
        { step: 'show interfaces trunk', note: 'Kommt VLAN-Verkehr über den Trunk an?' },
        { step: 'show ip route', note: 'Kennt der Router den Weg zum Ziel?' },
        { step: 'show arp / show mac address-table', note: 'Ist das Zielgerät im lokalen Netz bekannt?' },
      ],
      description: 'Eine sinnvolle Reihenfolge arbeitet sich von der physischen Verbindung nach oben durch.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.configuredVsFunctioning',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'vorgehen-classic',
    conceptCluster: 'troubleshooting.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      statement: 'Configured ≠ functioning. show running-config zeigt, was eingestellt ist; Betriebsbefehle zeigen, ob es tatsächlich funktioniert.',
      description: 'Eine korrekte Konfiguration allein beweist nicht, dass Nachbarn, Routen oder VLANs wirklich aktiv sind.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.portDown',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'vorgehen-classic',
    conceptCluster: 'troubleshooting.scenarios',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      symptom: 'Ein PC hat gar keine Verbindung.',
      firstCheck: 'show ip interface brief',
      followUp: 'Prüfe Kabel, Portstatus, Access-VLAN und ob der Port administrativ down ist.',
      description: 'Der schnellste Einstieg ist der Schnittstellenstatus.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.vlanMismatch',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'uebersicht-classic',
    conceptCluster: 'troubleshooting.scenarios',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      symptom: 'Ein Gerät landet im falschen VLAN.',
      firstCheck: 'show vlan brief oder show interfaces switchport',
      followUp: 'Korrigiere mit switchport access vlan <ID>.',
      description: 'VLAN-Zuweisungen prüft man direkt auf dem Switchport.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.trunkAllowed',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'uebersicht-classic',
    conceptCluster: 'troubleshooting.scenarios',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      symptom: 'VLAN-Verkehr kommt über einen Trunk nicht an.',
      firstCheck: 'show interfaces trunk',
      followUp: 'Prüfe, ob das VLAN in "allowed vlan" enthalten und auf dem Switch angelegt ist.',
      description: 'Eine zu enge allowed-VLAN-Liste ist eine klassische Fehlerursache.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.missingRoute',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'uebersicht-classic',
    conceptCluster: 'troubleshooting.scenarios',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      symptom: 'Ein entferntes Netz ist nicht erreichbar.',
      firstCheck: 'show ip route',
      followUp: 'Fehlt die Route, muss sie statisch eingetragen oder über dynamisches Routing gelernt werden.',
      description: 'Die Routing-Tabelle zeigt, ob ein Pfad zum Zielnetz bekannt ist.',
    },
    siblings: [],
  },
  {
    id: 'ciscoTroubleshooting.findDevice',
    topicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceTopicKey: CISCO_TROUBLESHOOTING_TOPIC_KEY,
    sourceSection: 'uebersicht-classic',
    conceptCluster: 'troubleshooting.scenarios',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      symptom: 'Ein Gerät im lokalen Netz ist nicht auffindbar.',
      firstCheck: 'show mac address-table',
      followUp: 'Zeigt, an welchem Port die MAC-Adresse gelernt wurde.',
      description: 'show mac address-table verknüpft MAC-Adressen mit physischen Ports.',
    },
    siblings: [],
  },
];
