// =============================================================================
// Knowledge Items – Cisco NAT
//
// Source: frontend/src/lib/academyLessons/ciscoNat.js
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const CISCO_NAT_TOPIC_KEY = topicKey('cisco-packet-tracer', 'nat');

export const ciscoNatKnowledgeItems = [
  {
    id: 'ciscoNat.purpose',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'nat.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      statement: 'NAT übersetzt private IPv4-Adressen in globale Adressen und umgekehrt.',
      note: 'NAT ist keine Firewall und ersetzt keine ACL/SPI, kann aber die Sichtbarkeit interner Netze reduzieren.',
      description: 'NAT ermöglicht internen Netzen mit privaten Adressen die Kommunikation mit externen Netzen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.insideOutside',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'inside-outside-classic',
    conceptCluster: 'nat.fundamentals',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'NAT-Router markieren Interfaces als inside (privates Netz) oder outside (externes Netz).',
      commands: ['ip nat inside', 'ip nat outside'],
      description: 'Ohne korrekte inside/outside-Kennzeichnung findet keine NAT-Übersetzung statt.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.addressTerms',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'address-terms-classic',
    conceptCluster: 'nat.fundamentals',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { term: 'Inside Local', meaning: 'Private Adresse des internen Geräts' },
        { term: 'Inside Global', meaning: 'Adresse, unter der das interne Gerät nach außen erscheint' },
        { term: 'Outside Global', meaning: 'Tatsächliche globale Adresse des externen Geräts' },
        { term: 'Outside Local', meaning: 'Adresse des externen Geräts aus Sicht des internen Netzes' },
      ],
      note: 'In einfachen Szenarien sind Outside Local und Outside Global identisch.',
      description: 'Cisco unterscheidet vier NAT-Adressbegriffe zur Beschreibung der Übersetzung.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.static',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'static-classic',
    conceptCluster: 'nat.types',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'Statisches NAT erstellt eine feste 1:1-Zuordnung zwischen Inside Local und Inside Global.',
      command: 'ip nat inside source static <inside-local> <inside-global>',
      useCase: 'Interner Server soll unter fester öffentlicher Adresse erreichbar sein.',
      description: 'Static NAT ist dauerhaft und eignet sich für Server, die von außen erreichbar sein sollen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.dynamic',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'dynamic-classic',
    conceptCluster: 'nat.types',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'Dynamisches NAT verwendet einen Pool globaler Adressen für interne Hosts.',
      commands: [
        'access-list <id> permit <internal-network> <wildcard>',
        'ip nat pool <name> <start> <end> netmask <mask>',
        'ip nat inside source list <ACL-ID> pool <POOL-NAME>',
      ],
      limitation: 'Pool kann erschöpft sein, wenn mehr gleichzeitige Verbindungen als globale Adressen vorhanden sind.',
      description: 'Dynamic NAT übersetzt ausgewählte interne Quellen in globale Pool-Adressen ohne Port-Sharing.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.pat',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'pat-classic',
    conceptCluster: 'nat.types',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'PAT (Port Address Translation) ermöglicht es, vielen internen Hosts dieselbe globale IP gemeinsam zu nutzen.',
      key: 'overload',
      examples: [
        { variant: 'Interface overload', command: 'ip nat inside source list 1 interface g0/1 overload' },
        { variant: 'Pool overload', command: 'ip nat inside source list 1 pool PUBLIC overload' },
      ],
      description: 'PAT unterscheidet Verbindungen über unterschiedliche Source-Ports auf der globalen Adresse.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.natAcl',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'dynamic-classic',
    conceptCluster: 'nat.configuration',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      statement: 'Die ACL bei NAT dient zur Auswahl der zu übersetzenden Inside-Local-Adressen.',
      misconception: 'Die NAT-ACL muss nicht zwingend mit ip access-group an ein Interface gebunden werden, um NAT zu ermöglichen.',
      effect: 'permit → Quelle wird übersetzt; deny → Quelle wird nicht übersetzt.',
      description: 'NAT verwendet die ACL intern, um festzulegen, welche Quell-IPs in den Übersetzungsprozess einbezogen werden.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.portForwarding',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'port-forward-classic',
    conceptCluster: 'nat.types',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'Port Forwarding leitet externe Anfragen auf globaler IP + Port an einen internen Host + Port weiter.',
      command: 'ip nat inside source static tcp <local-ip> <local-port> <global-ip> <global-port>',
      note: 'Externer und interner Port müssen nicht identisch sein.',
      useCase: 'Interner Server soll gezielt von außen erreichbar sein.',
      description: 'Port Forwarding ermöglicht eingehende Verbindungen zu internen Diensten.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.translationTable',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'translation-table-classic',
    conceptCluster: 'nat.verify',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      command: 'show ip nat translations',
      columns: ['Pro', 'Inside global', 'Inside local', 'Outside local', 'Outside global'],
      pat: 'Bei PAT sieht man zusätzlich die verwendeten Ports.',
      description: 'Die Translation Table zeigt alle aktiven NAT-Zuordnungen inklusive Protokoll und Adressen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.verify',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'verify-classic',
    conceptCluster: 'nat.verify',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { command: 'show ip nat translations', purpose: 'Aktive NAT-Übersetzungen anzeigen' },
        { command: 'show ip nat statistics', purpose: 'NAT-Status, inside/outside Interfaces, Hits/Misses' },
        { command: 'show ip interface', purpose: 'Kennzeichnung inside/outside prüfen' },
        { command: 'show running-config', purpose: 'Gesamte Konfiguration prüfen' },
      ],
      description: 'Verifizierung zeigt, ob NAT konfiguriert, gebunden und tatsächlich übersetzt.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.troubleshooting',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'troubleshooting-classic',
    conceptCluster: 'nat.troubleshoot',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.HARD,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      symptoms: [
        { symptom: 'NAT funktioniert nicht', cause: 'inside/outside falsch oder fehlend' },
        { symptom: 'Translation Table bleibt leer', cause: 'ACL matcht Quelle nicht, Routing fehlt, Traffic erreicht Router nicht' },
        { symptom: 'Dynamic NAT Pool erschöpft', cause: 'Mehr gleichzeitige Verbindungen als globale Adressen vorhanden' },
        { symptom: 'PAT funktioniert nicht', cause: 'overload fehlt' },
        { symptom: 'Interner Server nicht von außen erreichbar', cause: 'Port Forwarding fehlt oder falsche IP/Port' },
        { symptom: 'Port Forwarding konfiguriert, aber Zugriff blockiert', cause: 'ACL/SPI blockiert eingehenden Verkehr' },
      ],
      description: 'NAT-Fehler lassen sich über Interface-Kennzeichnung, ACL-Auswahl, Pool, overload, Port Forwarding und externe Filter eingrenzen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoNat.securityBoundary',
    topicKey: CISCO_NAT_TOPIC_KEY,
    sourceTopicKey: CISCO_NAT_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'nat.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      statement: 'NAT ist keine Firewall.',
      clarification: 'NAT verbirgt interne Adressen und verändert Erreichbarkeitsverhältnisse, ersetzt aber keine gezielte Sicherheitskontrolle wie ACL oder SPI.',
      description: 'NAT ändert Adressierung; Sicherheitsentscheidungen bleiben Aufgabe von Firewall, ACL und Stateful Inspection.',
    },
    siblings: [],
  },
];
