// =============================================================================
// Knowledge Items – Cisco ACLs
//
// Source: frontend/src/lib/academyLessons/ciscoAcl.js
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const CISCO_ACL_TOPIC_KEY = topicKey('cisco-packet-tracer', 'acl');

export const ciscoAclKnowledgeItems = [
  {
    id: 'ciscoAcl.processingOrder',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'first-match-classic',
    conceptCluster: 'acl.basics',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      statement: 'Eine ACL arbeitet Regeln von oben nach unten ab.',
      rule: 'Das erste passende Match gewinnt und stoppt die Auswertung.',
      description: 'Cisco ACLs verwenden First-Match-Logik: sobald eine Regel passt, wird permit/deny ausgeführt und die restlichen Regeln übersprungen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.implicitDeny',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'first-match-classic',
    conceptCluster: 'acl.basics',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'Am Ende jeder ACL wirkt automatisch ein unsichtbarer deny any / deny ip any any.',
      consequence: 'Wenn kein permit matcht, wird der Verkehr verworfen.',
      description: 'Der implicit deny sorgt dafür, dass Traffic ohne passende Regel blockiert wird.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.blocklistVsAllowlist',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'blocklist-allowlist-classic',
    conceptCluster: 'acl.basics',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      items: [
        { name: 'Blocklist', pattern: 'deny <unerwünscht>, dann permit any', note: 'Strenger Bereich, Rest wird erlaubt' },
        { name: 'Allowlist', pattern: 'permit <gewünscht>, Rest durch implicit deny', note: 'Strenger, nur explizit Erlaubtes kommt durch' },
      ],
      description: 'Allowlists sind für administrationskritische Bereiche wie VTY-Zugriff oft sicherer.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.standardAcl',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'standard-classic',
    conceptCluster: 'acl.standard',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      criteria: 'Filtert nur nach Source-IP / Source-Netz.',
      numberedRanges: '1–99, 1300–1999',
      placementRule: 'Typischerweise näher am Ziel, weil sie nur die Quelle kennt.',
      description: 'Standard ACLs filtern ausschließlich nach Source-IP und sollten daher vorsichtig platziert werden.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.extendedAcl',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'extended-classic',
    conceptCluster: 'acl.extended',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      criteria: 'Filtert nach Protokoll, Source, Destination, Port.',
      numberedRanges: '100–199, 2000–2699',
      placementRule: 'Kann präziser filtern und wird daher oft näher an der Quelle platziert.',
      description: 'Extended ACLs erlauben detaillierte Filterkriterien und damit präziseren Einsatz nahe der Quelle.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.hostAny',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'host-any-classic',
    conceptCluster: 'acl.syntax',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { keyword: 'host <IP>', meaning: 'Genau eine IP-Adresse', longForm: '<IP> 0.0.0.0' },
        { keyword: 'any', meaning: 'Beliebige Adresse', longForm: '0.0.0.0 255.255.255.255' },
      ],
      description: 'host und any sind Abkürzungen für Wildcard-Masken in ACLs.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.wildcard',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'wildcard-classic',
    conceptCluster: 'acl.syntax',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      rule: 'Wildcard-Maske = Invertierung der Subnetzmaske; 0 = muss passen, 255 = egal.',
      examples: [
        { subnet: '/24', wildcard: '0.0.0.255' },
        { subnet: '/30', wildcard: '0.0.0.3' },
      ],
      description: 'Die Wildcard-Maske in ACLs funktioniert wie bei OSPF und bestimmt, welche Bits der IP verglichen werden.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.binding',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'bind-classic',
    conceptCluster: 'acl.binding',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      interfaceCommand: 'ip access-group <ACL> in|out',
      vtyCommand: 'access-class <ACL> in',
      prerequisite: 'Eine ACL wirkt erst, wenn sie an ein Interface oder VTY gebunden ist.',
      description: 'ACLs müssen gebunden werden; ip access-group dient Interface-Traffic, access-class VTY-Management.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.inOutDirection',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'bind-classic',
    conceptCluster: 'acl.binding',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      in: 'Paket kommt über das Interface in den Router hinein.',
      out: 'Paket verlässt den Router über das Interface.',
      perspective: 'Richtungen werden aus Sicht des Router-Interfaces, nicht des Clients, bestimmt.',
      description: 'in/out beziehen sich auf den Datenfluss relativ zum Router-Interface.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.placement',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'position-classic',
    conceptCluster: 'acl.placement',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      items: [
        { type: 'Standard ACL', placement: 'eher näher am Ziel', reason: 'Filtert nur nach Source, könnte sonst zu viel blockieren' },
        { type: 'Extended ACL', placement: 'eher näher an der Quelle', reason: 'Kann präziser nach Protokoll/Destination/Port filtern' },
      ],
      note: 'Platzierung ist eine Faustregel und hängt von Topologie und Ziel ab.',
      description: 'Standard-ACLs sollten zielnäher, Extended-ACLs quellnäher platziert werden.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.onePerDirection',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'count-classic',
    conceptCluster: 'acl.binding',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      rule: 'Pro Interface, Protokoll und Richtung ist nur eine IPv4-ACL aktiv.',
      examples: [
        { possible: 'IPv4-ACL inbound + IPv4-ACL outbound auf g0/0' },
        { notPossible: 'Zwei IPv4-ACLs inbound auf g0/0' },
      ],
      description: 'Mehrere IPv4-ACLs in derselben Richtung auf demselben Interface sind nicht möglich.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.vtyAccessClass',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'vty-classic',
    conceptCluster: 'acl.vty',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      command: 'access-class <ACL> in',
      context: 'line vty 0 15',
      difference: 'An VTY-Lines wird access-class verwendet, nicht ip access-group.',
      description: 'access-class beschränkt Management-Zugriff (SSH/Telnet) auf bestimmte Quellnetze.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.sequenceEditing',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'edit-classic',
    conceptCluster: 'acl.editing',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.ORDERING],
    data: {
      statement: 'Named ACLs verwenden Sequenznummern, um Regeln einzufügen oder zu entfernen.',
      examples: [
        { action: 'Einfügen', command: '15 permit ...' },
        { action: 'Entfernen', command: 'no 15' },
        { action: 'Resequencing', command: 'ip access-list resequence <NAME> 10 10' },
      ],
      description: 'Sequenznummern ermöglichen gezieltes Editieren ohne Neuerstellung der ACL.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.verify',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'verify-classic',
    conceptCluster: 'acl.verify',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { command: 'show access-lists', purpose: 'Alle ACLs mit Regeln und Match-Zählern' },
        { command: 'show ip access-lists', purpose: 'Nur IPv4-ACLs mit Match-Zählern' },
        { command: 'show ip interface <IF>', purpose: 'ACL-Bindung und Richtung auf dem Interface' },
        { command: 'show running-config', purpose: 'Konfiguration inklusive ACLs und Bindungen' },
      ],
      description: 'Verifizierung zeigt Inhalt, Bindung und tatsächliche Treffer einer ACL.',
    },
    siblings: [],
  },
  {
    id: 'ciscoAcl.troubleshooting',
    topicKey: CISCO_ACL_TOPIC_KEY,
    sourceTopicKey: CISCO_ACL_TOPIC_KEY,
    sourceSection: 'analysis-classic',
    conceptCluster: 'acl.troubleshoot',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.HARD,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      symptoms: [
        { symptom: 'ACL existiert, hat keine Wirkung', cause: 'Nicht an Interface oder VTY gebunden' },
        { symptom: 'Falscher Traffic betroffen', cause: 'Falsches Interface oder falsche Richtung' },
        { symptom: 'Erlaubter Traffic wird blockiert', cause: 'Implicit deny greift, weil kein permit passt' },
        { symptom: 'Deny-Regel greift nie', cause: 'Eine vorherige permit any matcht zuerst' },
        { symptom: '0 matches', cause: 'Falsche Bindung/Richtung oder falscher Match' },
        { symptom: 'SSH-Zugriff betroffen', cause: 'access-class falsch oder ip access-group statt access-class' },
      ],
      description: 'ACL-Probleme lassen sich über Binding, Richtung, Regelreihenfolge und Match-Zähler eingrenzen.',
    },
    siblings: [],
  },
];
