// =============================================================================
// Knowledge Items – Cisco STP / PVST+ / PortFast / BPDU Guard
//
// Source: frontend/src/lib/academyLessons/ciscoStp.js
//
// Scope note: this file covers PVST+ specifics: Root Bridge election,
// Bridge ID / System-ID-Extension, port roles, port states, path cost,
// PortFast, BPDU Guard, err-disabled and verification commands.
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const CISCO_STP_TOPIC_KEY = topicKey('cisco-packet-tracer', 'stp');

export const ciscoStpKnowledgeItems = [
  {
    id: 'stp.loopProblem',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'problem-classic',
    conceptCluster: 'stp.loop',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    roleHints: ['technical', 'support'],
    data: {
      problem: 'Redundante Layer-2-Verbindungen ohne Loop-Schutz führen zu Broadcast-Storms, MAC-Instabilität und Mehrfachzustellung.',
      solution: 'STP blockiert gezielt Ports, um eine schleifenfreie Baumstruktur zu erzeugen, während die physische Redundanz erhalten bleibt.',
      description: 'STP verhindert Layer-2-Loops, ohne redundante Verbindungen entfernen zu müssen.',
    },
    siblings: [],
  },
  {
    id: 'stp.bridgeId',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'bridge-id-classic',
    conceptCluster: 'stp.rootBridge',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.MAPPING],
    roleHints: ['technical'],
    data: {
      components: [
        'Bridge Priority (0-61440, nur in 4096er-Schritten)',
        'System-ID-Extension (VLAN-ID bei PVST+)',
        'MAC-Adresse (Tie-Breaker)',
      ],
      rule: 'Die niedrigste Bridge ID gewinnt. Bei Gleichstand der Priority entscheidet die kleinste MAC-Adresse.',
      description: 'Die Bridge ID besteht aus Priority, VLAN-Anteil und MAC-Adresse. Niedrigster Wert wird Root Bridge.',
    },
    siblings: [],
  },
  {
    id: 'stp.pvst',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'pvst-classic',
    conceptCluster: 'stp.pvst',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    roleHints: ['technical'],
    data: {
      name: 'Per-VLAN Spanning Tree Plus',
      keyIdea: 'Jedes VLAN erhält einen eigenen Spanning Tree.',
      consequence: 'Blockierte Ports und Root Bridges können pro VLAN unterschiedlich sein - Lastverteilung und Redundanz pro VLAN.',
      description: 'PVST+ berechnet pro VLAN einen eigenen Spanning Tree, sodass jede VLAN eigene Root- und Portrollen haben kann.',
    },
    siblings: [],
  },
  {
    id: 'stp.portRoles',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'portrollen-classic',
    conceptCluster: 'stp.portRoles',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.MAPPING, QUESTION_ARCHETYPES.SCENARIO],
    roleHints: ['technical', 'support'],
    data: {
      roles: [
        { name: 'Root Port', meaning: 'Bester Pfad eines Nicht-Root-Switches zur Root Bridge. Pro Nicht-Root-Switch genau einer.' },
        { name: 'Designated Port', meaning: 'Bester Weg pro Segment zur Root Bridge; weiterleitend. Root-Bridge-Ports sind typischerweise Designated Ports.' },
        { name: 'Alternate / Non-Designated', meaning: 'Blockierter Ersatzweg, um Schleifen zu vermeiden.' },
      ],
      description: 'Portrollen beschreiben die Funktion eines Ports im Spannbaum, nicht unbedingt seinen aktuellen Weiterleitungszustand.',
    },
    siblings: [],
  },
  {
    id: 'stp.portStates',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'portzustaende-classic',
    conceptCluster: 'stp.portStates',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.ORDERING],
    roleHints: ['technical'],
    data: {
      states: [
        { name: 'Blocking', meaning: 'Empfängt BPDUs, leitet keine Daten weiter.' },
        { name: 'Listening', meaning: 'Nimmt an STP-Berechnung teil, leitet noch keine Daten weiter.' },
        { name: 'Learning', meaning: 'LERNT MAC-Adressen, leitet noch keine Daten weiter.' },
        { name: 'Forwarding', meaning: 'Normaler Betriebszustand, Daten werden weitergeleitet.' },
        { name: 'Disabled', meaning: 'Administrativ deaktiviert (shutdown).' },
      ],
      description: 'STP-Ports durchlaufen Zwischenzustände, um Schleifen beim Hochfahren zu vermeiden.',
    },
    siblings: [],
  },
  {
    id: 'stp.pathCost',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'path-cost-classic',
    conceptCluster: 'stp.pathCost',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    roleHints: ['technical'],
    data: {
      rule: 'STP summiert die Kosten entlang eines Pfads. Der Pfad mit der niedrigsten Gesamtsumme wird bevorzugt.',
      examples: [
        { speed: '100 Mbit/s', cost: '19' },
        { speed: '1000 Mbit/s', cost: '4' },
      ],
      description: 'Path Cost bewertet Verbindungen: schnellere Links haben niedrigere Kosten.',
    },
    siblings: [],
  },
  {
    id: 'stp.rootConfiguration',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'root-konfigurieren-classic',
    conceptCluster: 'stp.rootConfig',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.ORDERING, QUESTION_ARCHETYPES.SELECT_BEST],
    roleHints: ['technical'],
    data: {
      commands: [
        'spanning-tree vlan <ID> priority <Priority>',
        'spanning-tree vlan <ID> root primary',
        'spanning-tree vlan <ID> root secondary',
      ],
      note: 'Priority ist nur in 4096er-Schritten gültig (0, 4096, 8192, ..., 61440).',
      description: 'Root Bridge wird über Priority oder die Komfortbefehle root primary / secondary gezielt festgelegt.',
    },
    siblings: [],
  },
  {
    id: 'stp.portfast',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'portfast-bpduguard-classic',
    conceptCluster: 'stp.portfast',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    roleHints: ['technical'],
    data: {
      purpose: 'Überspringt Listening/Learning auf Endgeräte-Ports und wechselt sofort in Forwarding.',
      variants: [
        'spanning-tree portfast (Interface)',
        'spanning-tree portfast default (global)',
        'spanning-tree portfast trunk (Sonderfall, z. B. Router-on-a-Stick)',
      ],
      restriction: 'Nicht auf normalen Switch-zu-Switch-Uplinks aktivieren, da eine Schleife sofort weiterleiten würde.',
      description: 'PortFast beschleunigt die Konvergenz für Endgeräte-Ports, darf aber nicht auf Uplinks verwendet werden.',
    },
    siblings: [],
  },
  {
    id: 'stp.bpduGuard',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'portfast-bpduguard-classic',
    conceptCluster: 'stp.bpduGuard',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SCENARIO],
    roleHints: ['technical', 'support'],
    data: {
      command: 'spanning-tree bpduguard enable',
      trigger: 'PortFast-Port empfängt eine BPDU.',
      effect: 'Port wird in den Zustand err-disabled versetzt.',
      globalVariant: 'spanning-tree portfast bpduguard default',
      description: 'BPDU Guard schützt PortFast-Ports, indem er sie bei Empfang einer BPDU sofort deaktiviert (err-disabled).',
    },
    siblings: [],
  },
  {
    id: 'stp.errDisabledRecovery',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'err-disabled-classic',
    conceptCluster: 'stp.recovery',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.ORDERING, QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST],
    roleHints: ['technical', 'support'],
    data: {
      steps: [
        'Ursache beseitigen (angeschlossenes Gerät prüfen, BPDU-Quelle entfernen).',
        'Interface mit "shutdown" deaktivieren.',
        'Interface mit "no shutdown" reaktivieren.',
        'Mit "show interfaces status" verifizieren.',
      ],
      warning: 'Shutdown/no shutdown ohne Ursachenbehebung führt meist zu sofortigem erneutem err-disabled.',
      description: 'Ein BPDU-Guard-err-disabled-Port wird erst nach Behebung der Ursache mit shutdown/no shutdown wieder aktiviert.',
    },
    siblings: [],
  },
  {
    id: 'stp.verify',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'verifizierung-classic',
    conceptCluster: 'stp.verify',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    roleHints: ['technical'],
    data: {
      commands: [
        'show spanning-tree (Root ID, Bridge ID, Portrollen und -zustände)',
        'show spanning-tree vlan <ID> (pro VLAN bei PVST+)',
        'show spanning-tree summary (kompakte Übersicht)',
        'show spanning-tree detail (Detailcheck)',
        'show interfaces status (err-disabled erkennen)',
      ],
      interpretation: 'Root ID vs Bridge ID unterscheiden, Root/Desg/Altn-Rollen lesen, FWD/BLK-Zustände lesen, err-disabled erkennen.',
      description: 'STP wird mit show spanning-tree-Befehlen und show interfaces status verifiziert.',
    },
    siblings: [],
  },
  {
    id: 'stp.roleVsState',
    topicKey: CISCO_STP_TOPIC_KEY,
    sourceTopicKey: CISCO_STP_TOPIC_KEY,
    sourceSection: 'portrollen-classic',
    conceptCluster: 'stp.concepts',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.COMPARE],
    roleHints: ['technical', 'support'],
    data: {
      items: [
        { name: 'Port Role', meaning: 'Funktion im Spannbaum (Root / Designated / Alternate).' },
        { name: 'Port State', meaning: 'Aktueller Weiterleitungszustand (Blocking / Listening / Learning / Forwarding).' },
      ],
      example: 'Ein Alternate Port befindet sich typischerweise im Blocking-Zustand.',
      description: 'Rolle und Zustand sind zwei unterschiedliche Dimensionen eines STP-Ports.',
    },
    siblings: [],
  },
];
