// =============================================================================
// Knowledge Items – Cisco SSH / Remote Management
//
// Source: frontend/src/lib/academyLessons/ciscoSsh.js
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const CISCO_SSH_TOPIC_KEY = topicKey('cisco-packet-tracer', 'ssh');

export const ciscoSshKnowledgeItems = [
  {
    id: 'ciscoSsh.purpose',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'telnet-vs-ssh-classic',
    conceptCluster: 'ssh.fundamentals',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      statement: 'SSH verschlüsselt die gesamte Fernwartungsverbindung, Telnet überträgt alles im Klartext.',
      comparison: [
        { protocol: 'Telnet', port: 23, security: 'Klartext, unsicher' },
        { protocol: 'SSH', port: 22, security: 'Verschlüsselt' },
      ],
      description: 'Für die sichere Fernadministration wird SSH anstelle von Telnet verwendet.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.version',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'ssh-version-classic',
    conceptCluster: 'ssh.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      statement: 'SSHv1 hat bekannte Sicherheitsschwächen und sollte nicht verwendet werden.',
      command: 'ip ssh version 2',
      description: 'Auf Cisco-Geräten sollte explizit SSH Version 2 erzwungen werden.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.dependencyChain',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'konfig-reihenfolge-classic',
    conceptCluster: 'ssh.configuration',
    type: KNOWLEDGE_TYPES.ORDER,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.ORDERING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      statement: 'SSH benötigt eine bestimmte Konfigurationsreihenfolge, weil jeder Schritt auf Voraussetzungen aufbaut.',
      order: [
        { step: 'Hostname', note: 'Teil des RSA-Schlüsselnamens' },
        { step: 'Domain Name', note: 'Teil des RSA-Schlüsselnamens' },
        { step: 'enable secret', note: 'Privilegierten Modus absichern' },
        { step: 'username secret', note: 'Lokale Benutzerdatenbank' },
        { step: 'crypto key generate rsa', note: 'Erzeugt das Schlüsselpaar' },
        { step: 'ip ssh version 2', note: 'SSHv2 erzwingen' },
        { step: 'IP-Erreichbarkeit', note: 'Interface oder SVI aktiv' },
        { step: 'line vty + login local + transport input ssh', note: 'VTY absichern' },
      ],
      description: 'Hostname und Domain Name müssen vor dem RSA-Schlüssel vorhanden sein; login local setzt einen lokalen Benutzer voraus.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.rsaKey',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'befehle-classic',
    conceptCluster: 'ssh.configuration',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      statement: 'crypto key generate rsa erzeugt das RSA-Schlüsselpaar, das SSH für die Verschlüsselung benötigt.',
      dependency: 'Hostname und Domain Name müssen zuvor konfiguriert sein, damit der Schlüsselname (Hostname.Domainname) gebildet werden kann.',
      note: 'Für den Lehrgang verwenden wir mindestens 1024 Bit Modulus.',
      description: 'Ohne RSA-Schlüssel ist SSH auf dem Gerät nicht aktiv.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.vty',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'befehle-classic',
    conceptCluster: 'ssh.configuration',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      statement: 'VTY-Lines müssen für SSH konfiguriert werden: login local verwendet die lokale Benutzerdatenbank, transport input ssh erlaubt nur SSH.',
      commands: ['line vty 0 15', 'login local', 'transport input ssh'],
      description: 'SSH allein schließt Telnet nicht aus; transport input ssh ist nötig, um Telnet auf den VTY-Lines zu verbieten.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.managementSvi',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'l2-switch-szenario-classic',
    conceptCluster: 'ssh.devices',
    type: KNOWLEDGE_TYPES.PROCEDURE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'Ein reiner Layer-2-Switch erhält die Management-IP über eine SVI in einem eigenen Management-VLAN.',
      commands: ['vlan <ID>', 'name <Name>', 'interface vlan <ID>', 'ip address <IP> <Mask>', 'no shutdown'],
      note: 'Access-Ports können auf einem L2-Switch keine IP-Adresse tragen.',
      description: 'Die Management-SVI trennt Verwaltung vom Nutzdatenverkehr und ist unabhängig von einzelnen physischen Ports erreichbar.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.defaultGatewaySwitch',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'l2-switch-szenario-classic',
    conceptCluster: 'ssh.devices',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      statement: 'Ein reiner L2-Switch braucht für SSH-Erreichbarkeit aus anderen Netzen ein ip default-gateway.',
      command: 'ip default-gateway <IP>',
      description: 'Weil ein L2-Switch nicht selbst routet, zeigt das Default Gateway auf das nächste Routing-Gerät.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.deviceDifferences',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'gemeinsamkeiten-classic',
    conceptCluster: 'ssh.devices',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'SSH-Grundkonfiguration ist auf Router, L2-Switch und Multilayer-Switch identisch; nur die IP-Erreichbarkeit unterscheidet sich.',
      differences: [
        { device: 'Router', ipReachability: 'Physisches Interface' },
        { device: 'L2-Switch', ipReachability: 'SVI im Management-VLAN + ip default-gateway' },
        { device: 'Multilayer-Switch', ipReachability: 'SVI (oder physisches Interface), ggf. ip routing' },
      ],
      description: 'Hostname, Domain, Benutzer, RSA-Key, SSHv2 und VTY sind bei allen dreien gleich.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.verify',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'verifizierung-classic',
    conceptCluster: 'ssh.verify',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { command: 'show ip ssh', purpose: 'SSH-Version und Verbindungsstatus' },
        { command: 'show crypto key mypubkey rsa', purpose: 'Existenz eines RSA-Schlüssels prüfen' },
        { command: 'show ssh', purpose: 'Aktive SSH-Sitzungen anzeigen' },
        { command: 'show running-config | include vty', purpose: 'VTY-Konfiguration prüfen' },
        { command: 'show ip interface brief', purpose: 'Management-Interface/SVI-Status prüfen' },
      ],
      description: 'Verifizierung zeigt, ob SSH aktiv ist und wie die VTY-/IP-Konfiguration aussieht.',
    },
    siblings: [],
  },
  {
    id: 'ciscoSsh.troubleshooting',
    topicKey: CISCO_SSH_TOPIC_KEY,
    sourceTopicKey: CISCO_SSH_TOPIC_KEY,
    sourceSection: 'troubleshooting-classic',
    conceptCluster: 'ssh.troubleshoot',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.HARD,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      symptoms: [
        { symptom: '"% Please configure a hostname..."', cause: 'Hostname fehlt' },
        { symptom: 'crypto key generate rsa schlägt fehl', cause: 'Hostname oder Domain Name fehlt' },
        { symptom: 'show ip ssh zeigt SSH disabled', cause: 'RSA-Schlüssel fehlt oder SSHv2 nicht aktiviert' },
        { symptom: 'Verbindung wird sofort abgelehnt', cause: 'RSA-Schlüssel fehlt oder SSH nicht aktiviert' },
        { symptom: 'Login wird trotz korrekter Daten abgelehnt', cause: 'login local ohne passenden Benutzer' },
        { symptom: 'Gerät nicht per Ping erreichbar', cause: 'Management-IP/SVI fehlt, falsch oder down' },
        { symptom: 'SSH aus gleichem VLAN klappt, aus anderem Netz nicht (L2-Switch)', cause: 'ip default-gateway fehlt oder falsch' },
        { symptom: 'Telnet funktioniert weiterhin', cause: 'transport input ssh fehlt auf den VTY-Lines' },
      ],
      description: 'SSH-Fehler lassen sich entlang der Abhängigkeitskette eingrenzen: Hostname/Domain → RSA → SSHv2 → IP-Erreichbarkeit → VTY.',
    },
    siblings: [],
  },
];
