// =============================================================================
// Knowledge Items – Cisco OSPF
//
// Source: frontend/src/lib/academyLessons/ciscoOspf.js
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const CISCO_OSPF_TOPIC_KEY = topicKey('cisco-packet-tracer', 'ospf');

export const ciscoOspfKnowledgeItems = [
  {
    id: 'ciscoOspf.linkState',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'ospf.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      statement: 'OSPF ist ein link-state dynamisches Routing-Protokoll.',
      detail: 'Jeder Router kennt die Topologie seiner Area und berechnet mit SPF/Dijkstra den kürzesten Pfad.',
      description: 'OSPF tauscht Link-State-Informationen aus und berechnet Routingentscheidungen aus der Topologie.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.singleAreaArea0',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'ospf.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      statement: 'Single-Area OSPF verwendet in diesem Lehrgang typischerweise Area 0 als Backbone-Area.',
      description: 'Alle Router und Interfaces gehören in Single-Area-OSPF zu einer Area, üblicherweise Area 0.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.processId',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'ospf.fundamentals',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: 'Die OSPF-Prozess-ID ist lokal und muss nicht auf allen Nachbarn identisch sein.',
      contrast: 'Area und ggf. Authentifizierung müssen auf dem Verbindungsinterface übereinstimmen.',
      description: 'router ospf <ID> startet lokal eine OSPF-Instanz; die ID ist nicht Teil der Nachbarschaftsbedingungen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.wildcardMask',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'wildcard-classic',
    conceptCluster: 'ospf.wildcard',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      rule: 'Wildcard-Maske = Invertierung der Subnetzmaske; 0 = Bit muss passen, 255 = Bit ist egal.',
      examples: [
        { subnetMask: '255.255.255.0', wildcard: '0.0.0.255' },
        { subnetMask: '255.255.255.252', wildcard: '0.0.0.3' },
      ],
      description: 'Die Wildcard-Maske in der network-Anweisung bestimmt, welche Interface-IPs für OSPF ausgewählt werden.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.networkMatchesInterfaces',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'network-method-classic',
    conceptCluster: 'ospf.network',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      statement: 'Der network-Befehl im OSPF-Prozess prüft lokale Interface-IPs gegen Adresse und Wildcard.',
      consequence: 'Matchende Interfaces nehmen am OSPF-Prozess teil; ihre verbundenen Netze werden in OSPF eingebracht.',
      description: 'network <addr> <wildcard> area 0 aktiviert OSPF auf allen passenden Interfaces, nicht nur auf einem bestimmten Netz.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.activationMethods',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'network-method-classic',
    conceptCluster: 'ospf.network',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.MATCHING],
    data: {
      items: [
        { method: 'Network-Methode', command: 'router ospf 1 → network <addr> <wildcard> area 0' },
        { method: 'Interface-Methode', command: 'interface <if> → ip ospf 1 area 0' },
      ],
      description: 'Beide Methoden aktivieren OSPF auf Interfaces; in diesem Lehrgang liegt der Schwerpunkt auf der Network-Methode.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.neighborRequirements',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'intro-classic',
    conceptCluster: 'ospf.neighbor',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      requirements: [
        'OSPF muss auf beiden Interfaces aktiv sein.',
        'Interfaces müssen im selben Subnetz erreichbar sein.',
        'Area auf dem gemeinsamen Interface muss übereinstimmen.',
        'Hello-/Dead-Intervalle müssen passen.',
        'Authentifizierungstyp und Schlüssel müssen übereinstimmen.',
      ],
      notRequired: 'Gleiche OSPF-Prozess-ID.',
      description: 'OSPF-Nachbarschaften setzen übereinstimmende Parameter auf dem Verbindungsinterface voraus, nicht die gleiche Prozess-ID.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.passiveInterface',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'passive-classic',
    conceptCluster: 'ospf.passive',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      statement: 'passive-interface beendet Hello-Pakete auf einem Interface, bewirbt das angehängte Netz aber weiterhin.',
      commonUse: 'Client-/LAN-Interfaces ohne erwarteten OSPF-Nachbarn.',
      misconception: 'passive-interface nimmt das Netz nicht automatisch komplett aus OSPF heraus.',
      description: 'passive-interface verhindert Nachbarschaften auf dem Interface, das Netz wird aber weiter über OSPF angekündigt.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.passiveInterfaceDefault',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'passive-classic',
    conceptCluster: 'ospf.passive',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      statement: 'passive-interface default macht alle Interfaces passiv; no passive-interface hebt dies für ausgewählte Interfaces auf.',
      description: 'Diese Kombination ist eine sichere Admin-Routine, um nur auf Uplink-Interfaces Nachbarschaften zuzulassen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.cost',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'cost-classic',
    conceptCluster: 'ospf.cost',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      rule: 'OSPF wählt den Pfad mit den niedrigsten Gesamtkosten.',
      detail: 'Cost hängt von der Bandbreite ab; schnellere Links haben üblicherweise niedrigere Kosten.',
      ecmp: 'Bei gleichen Kosten kann OSPF mehrere Pfade parallel nutzen (Equal-Cost Multipath).',
      description: 'Die OSPF-Metrik basiert auf den Link-Kosten; niedrigere Gesamtkosten werden bevorzugt.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.defaultOriginate',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'default-route-classic',
    conceptCluster: 'ospf.default',
    type: KNOWLEDGE_TYPES.RELATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.ORDERING, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      statement: '"default-information originate" verteilt eine bereits vorhandene statische Default Route über OSPF.',
      prerequisite: 'Die statische Default Route muss zuerst konfiguriert sein (z. B. ip route 0.0.0.0 0.0.0.0 <next-hop>).',
      misconception: 'default-information originate erstellt nicht automatisch eine Default Route.',
      description: 'Der Befehl bewirbt eine vorhandene Default Route an OSPF-Nachbarn.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.verify',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'verify-classic',
    conceptCluster: 'ospf.verify',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      mapping: [
        { command: 'show ip ospf neighbor', purpose: 'Zeigt OSPF-Nachbarn und deren Zustand (z. B. FULL)' },
        { command: 'show ip route ospf', purpose: 'Zeigt ausschließlich über OSPF gelernte Routen' },
        { command: 'show ip protocols', purpose: 'Zeigt OSPF-Prozess, Router-ID und Netzwerke' },
        { command: 'show ip ospf interface', purpose: 'Zeigt OSPF-Status pro Interface' },
        { command: 'show running-config', purpose: 'Zeigt die konfigurierten Befehle' },
        { command: 'clear ip ospf process', purpose: 'Startet den OSPF-Prozess neu' },
      ],
      description: 'Mit diesen Befehlen lässt sich OSPF konfigurieren, verifizieren und neu starten.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.troubleshooting',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'troubleshooting-classic',
    conceptCluster: 'ospf.troubleshoot',
    type: KNOWLEDGE_TYPES.TROUBLESHOOT,
    difficulty: DIFFICULTY.HARD,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.TROUBLESHOOT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      symptoms: [
        { symptom: 'Kein OSPF-Nachbar in show ip ospf neighbor', cause: 'OSPF nicht aktiv, falsche Area, passive auf Verbindungsinterface, Authentifizierungsmismatch oder Interface down' },
        { symptom: 'Neighbor FULL, aber Route fehlt', cause: 'Zielnetz nicht korrekt in OSPF aktiviert (network/Wildcard falsch)' },
        { symptom: 'Route über unerwarteten Pfad', cause: 'OSPF Cost unterschiedlich' },
        { symptom: 'Default Route nicht gelernt', cause: 'default-information originate fehlt oder statische Default Route fehlt' },
      ],
      description: 'OSPF-Fehler lassen sich durch Nachbar-Status, Routingtabelle und Konfiguration eingrenzen.',
    },
    siblings: [],
  },
  {
    id: 'ciscoOspf.authentication',
    topicKey: CISCO_OSPF_TOPIC_KEY,
    sourceTopicKey: CISCO_OSPF_TOPIC_KEY,
    sourceSection: 'auth-clear-classic',
    conceptCluster: 'ospf.security',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.MATCHING],
    data: {
      items: [
        { type: 'Typ 0', name: 'Keine Authentifizierung', note: 'Standard, unsicher' },
        { type: 'Typ 1', name: 'Klartext', note: 'Schlüssel wird im Klartext übertragen' },
        { type: 'Typ 2', name: 'Message-Digest (MD5)', note: 'Im Cisco-/Packet-Tracer-Kontext gezeigt' },
      ],
      keyPoint: 'Beide Nachbarn müssen denselben Authentifizierungstyp und Schlüssel verwenden.',
      description: 'OSPF-Authentifizierung muss auf beiden Seiten übereinstimmen, sonst entsteht keine Nachbarschaft.',
    },
    siblings: [],
  },
];
