// =============================================================================
// Knowledge Items – IPv4 & Subnetting
//
// Sources:
//   - frontend/src/lib/academyLessons/ipv4.js
//   - frontend/src/lib/academyLessons/subnetMasks.js
//   - frontend/src/lib/academyLessons/subnetting.js
// Math reference: frontend/src/lib/networking/ipv4Math.js
// =============================================================================

import { topicKey } from '../../academyTopics.js';
import { KNOWLEDGE_TYPES, QUESTION_ARCHETYPES, DIFFICULTY } from '../types.js';

export const IPV4_TOPIC_KEY = topicKey('fundamentals', 'ipv4');
export const SUBNET_MASKS_TOPIC_KEY = topicKey('fundamentals', 'subnet-masks');
export const SUBNETTING_TOPIC_KEY = topicKey('fundamentals', 'subnetting');

export const ipv4SubnettingKnowledgeItems = [
  // ---------------------------------------------------------------------------
  // IPv4 structure & properties
  // ---------------------------------------------------------------------------
  {
    id: 'ipv4.definition',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'ip-role-classic',
    conceptCluster: 'ipv4.basics.definition',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'IP-Adresse',
      definition: 'Eine logische Adresse einer Netzwerkschnittstelle auf OSI-Layer 3, die netzübergreifende Adressierung und Weiterleitung ermöglicht.',
      description: 'Ein System kann mehrere Schnittstellen und IP-Adressen besitzen; Router verwenden IP-Informationen für Weiterleitungsentscheidungen.',
      distractorDefinitions: ['Eine ausschließlich lokale Layer-2-Adresse für Ethernet-Frames.', 'Eine Portnummer zur Auswahl eines Dienstes.', 'Eine physische Seriennummer des gesamten Computers.'],
    },
    siblings: [],
  },
  {
    id: 'ipv4.ipVsMac',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'ip-role-classic',
    conceptCluster: 'ipv4.basics.ipVsMac',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      compareOn: 'description',
      items: [
        { name: 'MAC-Adresse', description: 'Lokale Layer-2-Adressierung eines Frames auf dem konkreten Link.' },
        { name: 'IP-Adresse', description: 'Logische Layer-3-Adressierung für Kommunikation über Netzwerkgrenzen hinweg.' },
      ],
      description: 'MAC und IP ergänzen sich und erfüllen nicht dieselbe Aufgabe.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.ipVersions',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'ip-versions-classic',
    conceptCluster: 'ipv4.basics.versions',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      compareOn: 'description',
      items: [
        { name: 'IPv4', description: '32 Bit, vier 8-Bit-Oktette, menschenlesbar meist in Dezimalpunktschreibweise.' },
        { name: 'IPv6', description: '128 Bit, vollständig acht Blöcke mit je vier Hexadezimalstellen.' },
      ],
      description: 'Mehr Bits ermöglichen bei IPv6 einen wesentlich größeren möglichen Adressraum; zeitabhängige Verbreitungszahlen sind kein Lernziel.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.structure',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'structure-classic',
    conceptCluster: 'ipv4.structure',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      totalBits: 32,
      octets: 4,
      bitsPerOctet: 8,
      notation: 'punktierte Dezimalnotation',
      description: 'Eine IPv4-Adresse hat 32 Bit, aufgeteilt in vier Oktette zu je 8 Bit.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.privateRanges',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'private-classic',
    conceptCluster: 'ipv4.ranges',
    type: KNOWLEDGE_TYPES.RANGE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MAPPING, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      ranges: [
        { network: '10.0.0.0/8', label: '10.0.0.0/8' },
        { network: '172.16.0.0/12', label: '172.16.0.0/12' },
        { network: '192.168.0.0/16', label: '192.168.0.0/16' },
      ],
      description: 'Private Adressen werden in internen Netzen verwendet und im öffentlichen Internet nicht direkt geroutet.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.loopback',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'private-classic',
    conceptCluster: 'ipv4.special',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'Loopback-Bereich: ein Gerät spricht mit sich selbst.',
      range: '127.0.0.0/8',
      typical: '127.0.0.1',
      meaning: 'Loopback: Ein Gerät spricht mit sich selbst.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.apipa',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'private-classic',
    conceptCluster: 'ipv4.special',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'APIPA/Link-Local-Bereich: zeigt oft an, dass kein DHCP erreichbar war.',
      range: '169.254.0.0/16',
      meaning: 'Link-Local/APIPA: deutet oft darauf hin, dass kein DHCP erreichbar war.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.networkHost',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'network-host-classic',
    conceptCluster: 'ipv4.networkHost.property',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      subject: 'Netz- und Hostanteil',
      description: 'Der Netzanteil identifiziert das gemeinsame Netz; der Hostanteil unterscheidet einen Teilnehmer innerhalb dieses Netzes.',
      distractorDescriptions: ['Beide Anteile enthalten ausschließlich Portnummern.', 'Der Hostanteil identifiziert immer das gesamte Internet.', 'Der Netzanteil ist eine physische MAC-Adresse.'],
    },
    siblings: [],
  },
  {
    id: 'ipv4.addressRoles',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'address-roles-classic',
    conceptCluster: 'ipv4.addressRoles.mapping',
    type: KNOWLEDGE_TYPES.MAPPING,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.MATCHING, QUESTION_ARCHETYPES.MAPPING],
    data: {
      subject: 'Adressrollen',
      pairs: [
        { key: 'alle Hostbits 0', value: 'Netz-ID' },
        { key: 'Hostbits zwischen den Grenzen', value: 'Hostadresse' },
        { key: 'alle Hostbits 1', value: 'Broadcastadresse' },
      ],
      description: 'Netz-ID und Broadcast begrenzen den normalen Hostbereich eines klassischen IPv4-Netzes.',
    },
    siblings: [],
  },
  {
    id: 'ipv4.limitedBroadcast',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'private-classic',
    conceptCluster: 'ipv4.special',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      subject: '255.255.255.255',
      description: 'Limited Broadcast für das lokale Netzsegment; die Adresse richtet sich nicht an jeden Rechner im Internet.',
      distractorDescriptions: ['Loopback-Adresse für den eigenen TCP/IP-Stack.', 'Private Hostadresse aus dem 10.0.0.0/8-Bereich.', 'Default Route für alle unbekannten Ziele.'],
    },
    siblings: ['ipv4.loopback', 'ipv4.apipa', 'ipv4.defaultRoute'],
  },
  {
    id: 'ipv4.defaultRoute',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'private-classic',
    conceptCluster: 'ipv4.special',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      subject: '0.0.0.0/0',
      description: 'Umfasst den gesamten IPv4-Adressraum und wird im Routing als Default Route für nicht spezifischer bekannte Ziele verwendet.',
      distractorDescriptions: ['Limited Broadcast für das lokale Netzsegment.', 'Loopback-Adresse des eigenen Rechners.', 'APIPA-Bereich nach fehlgeschlagenem DHCP-Bezug.'],
    },
    siblings: ['ipv4.loopback', 'ipv4.apipa', 'ipv4.limitedBroadcast'],
  },
  {
    id: 'ipv4.classfulVsCidr',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'classful-classic',
    conceptCluster: 'ipv4.classful.property',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      subject: 'klassenbasierter Adressierung und CIDR',
      description: 'Historische Klassen verwendeten starre Netzgrößen; modernes CIDR erlaubt flexible Präfixe und reduziert unnötige Adressverschwendung.',
      distractorDescriptions: ['CIDR zwingt jede Adresse ab 192 automatisch in ein /24-Netz.', 'Netzklassen sind flexible Präfixe zwischen /0 und /32.', 'CIDR ersetzt IPv4-Adressen vollständig durch MAC-Adressen.'],
    },
    siblings: [],
  },
  {
    id: 'ipv4.blockSizeIntro',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'jump-intro-classic',
    conceptCluster: 'ipv4.blockSize.property',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      subject: 'Sprungweite',
      description: 'Abstand aufeinanderfolgender Netz-IDs im relevanten Oktett; bei /27 beträgt er 32.',
      distractorDescriptions: ['Anzahl erreichbarer DNS-Server innerhalb des betrachteten lokalen IPv4-Netzes.', 'Abstand zwischen zwei aufeinanderfolgenden TCP-Portnummern eines erreichbaren Dienstes.', 'Anzahl der dezimal geschriebenen Oktette innerhalb einer vollständigen IPv4-Adresse.'],
    },
    siblings: [],
  },
  {
    id: 'ipv4.cidrPrefix',
    topicKey: IPV4_TOPIC_KEY,
    sourceTopicKey: IPV4_TOPIC_KEY,
    sourceSection: 'prefix-classic',
    conceptCluster: 'ipv4.cidr',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      min: 0,
      max: 32,
      description: 'Der CIDR-Präfix gibt an, wie viele Bits zum Netzanteil gehören.',
    },
    siblings: [],
  },

  // ---------------------------------------------------------------------------
  // Subnet masks / CIDR mapping
  // ---------------------------------------------------------------------------
  {
    id: 'subnetMasks.prefixToMask',
    topicKey: SUBNET_MASKS_TOPIC_KEY,
    sourceTopicKey: SUBNET_MASKS_TOPIC_KEY,
    sourceSection: 'prefix-to-mask-classic',
    conceptCluster: 'subnetting.mask',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.MAPPING, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'Bestimme die Subnetzmaske zu einem gegebenen Präfix.',
      calculationFamily: 'prefixToMask',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26 },
        medium: { prefixMin: 16, prefixMax: 30 },
        hard: { prefixMin: 8, prefixMax: 30 },
      },
      distractorStrategy: 'prefixToMask',
    },
    siblings: [],
  },
  {
    id: 'subnetMasks.maskToPrefix',
    topicKey: SUBNET_MASKS_TOPIC_KEY,
    sourceTopicKey: SUBNET_MASKS_TOPIC_KEY,
    sourceSection: 'bitwerte-classic',
    conceptCluster: 'subnetting.mask',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      description: 'Bestimme den Präfix zu einer gegebenen Subnetzmaske.',
      calculationFamily: 'maskToPrefix',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26 },
        medium: { prefixMin: 16, prefixMax: 30 },
        hard: { prefixMin: 8, prefixMax: 30 },
      },
      distractorStrategy: 'maskToPrefix',
    },
    siblings: [],
  },

  // ---------------------------------------------------------------------------
  // Subnetting calculations
  // ---------------------------------------------------------------------------
  {
    id: 'subnetting.definition',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'subnetting-concept-classic',
    conceptCluster: 'subnetting.concept.definition',
    type: KNOWLEDGE_TYPES.DEFINITION,
    difficulty: DIFFICULTY.EASY,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.RECALL, QUESTION_ARCHETYPES.SELECT_BEST],
    data: {
      term: 'Subnetting',
      definition: 'Aufteilung eines vorhandenen IP-Netzes in mehrere kleinere Netze durch Verlängern des Netzanteils.',
      description: 'Subnetting erzeugt keine neuen IPv4-Adressen: Mehr Netzbits bedeuten mehr, aber kleinere Subnetze und weniger Hosts je Subnetz.',
      distractorDefinitions: ['Erzeugen zusätzlicher IPv4-Adressen außerhalb des vorhandenen Adressraums.', 'Zusammenfassen mehrerer Netze zu einem größeren Block.', 'Ersetzen von IP-Adressen durch MAC-Adressen.'],
    },
    siblings: [],
  },
  {
    id: 'subnetting.requirementTypes',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'requirements-classic',
    conceptCluster: 'subnetting.requirements.compare',
    type: KNOWLEDGE_TYPES.COMPARE,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.COMPARE, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      compareOn: 'description',
      items: [
        { name: 'Netzanzahl gegeben', description: 'Kleinstes n mit 2^n ≥ benötigte gleich große Subnetze; n wird zum Ausgangspräfix addiert.' },
        { name: 'Hostbedarf gegeben', description: 'Kleinstes h mit 2^h − 2 ≥ benötigte Hosts; 32 − h ergibt das neue Präfix.' },
      ],
      description: 'Vor der Rechnung muss klar sein, ob zusätzliche Netzbits oder ausreichende Hostbits gesucht werden.',
    },
    siblings: [],
  },
  {
    id: 'subnetting.borrowBits',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'subnetting-concept-classic',
    conceptCluster: 'subnetting.tradeoff.property',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.RECALL],
    data: {
      subject: 'Umwandeln von Hostbits in Netzbits',
      description: 'Mehr Netzbits ermöglichen mehr Subnetze, lassen aber weniger Hostbits und damit weniger Hosts pro Subnetz übrig.',
      distractorDescriptions: ['Die Gesamtzahl verfügbarer IPv4-Adressen wächst dadurch automatisch.', 'Mehr Netzbits erhöhen gleichzeitig die Hostkapazität jedes Subnetzes.', 'Der Präfix wird kleiner und das einzelne Subnetz dadurch größer.'],
    },
    siblings: [],
  },
  {
    id: 'subnetting.sixSubnetsMisconception',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'subnet-count-classic',
    conceptCluster: 'subnetting.misconception.property',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      subject: 'der Aussage „Sechs Subnetze benötigen sechs zusätzliche Netzbits“',
      description: 'Falsch: Gesucht ist die kleinste Zweierpotenz. Drei Bits liefern 2³ = 8 mögliche Subnetze und reichen damit für sechs Anforderungen.',
      distractorDescriptions: ['Richtig: Jedes gewünschte Subnetz benötigt unabhängig vom Ausgangspräfix genau ein zusätzliches Bit.', 'Richtig: Sechs Bits liefern genau sechs mögliche Kombinationen und keine weiteren Netze.', 'Falsch: Bereits ein einziges Bit liefert grundsätzlich mindestens sechs unterschiedliche Subnetze.'],
    },
    siblings: [],
  },
  {
    id: 'subnetting.fifteenHostsMisconception',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'host-count-classic',
    conceptCluster: 'subnetting.misconception.property',
    type: KNOWLEDGE_TYPES.PROPERTY,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.TROUBLESHOOT],
    data: {
      subject: 'der Aussage „Vier Hostbits reichen für 15 Hosts“',
      description: 'Falsch für normale Hostnetze: 2⁴ = 16 Gesamtadressen, nach Netz-ID und Broadcast bleiben nur 14 nutzbare Hosts; benötigt werden fünf Hostbits.',
      distractorDescriptions: ['Richtig: Netz-ID und Broadcast können denselben Geräten wie normale Hostadressen zugewiesen werden.', 'Richtig: Vier Hostbits ergeben ohne weitere Einschränkung grundsätzlich mindestens 15 nutzbare Hostadressen.', 'Falsch: Vier Hostbits stellen insgesamt nur vier Adressen dar und reichen deshalb nicht aus.'],
    },
    siblings: [],
  },
  {
    id: 'subnetting.networkId',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'classic-method',
    conceptCluster: 'subnetting.calculation',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'Berechne die Netz-ID aus IP und Präfix.',
      calculationFamily: 'subnetting',
      target: 'networkId',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26, allowOctetChange: false, privateOnly: true },
        medium: { prefixMin: 16, prefixMax: 30, allowOctetChange: true, privateOnly: true },
        hard: { prefixMin: 8, prefixMax: 30, allowOctetChange: true, privateOnly: true },
      },
      distractorStrategy: 'subnettingNetworkId',
    },
    siblings: [
      'subnetting.broadcast',
      'subnetting.firstHost',
      'subnetting.lastHost',
      'subnetting.usableHosts',
      'subnetting.jumpSize',
    ],
  },
  {
    id: 'subnetting.broadcast',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'classic-method',
    conceptCluster: 'subnetting.calculation',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'Berechne die Broadcast-Adresse aus IP und Präfix.',
      calculationFamily: 'subnetting',
      target: 'broadcast',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26, allowOctetChange: false, privateOnly: true },
        medium: { prefixMin: 16, prefixMax: 30, allowOctetChange: true, privateOnly: true },
        hard: { prefixMin: 8, prefixMax: 30, allowOctetChange: true, privateOnly: true },
      },
      distractorStrategy: 'subnettingBroadcast',
    },
    siblings: [
      'subnetting.networkId',
      'subnetting.firstHost',
      'subnetting.lastHost',
      'subnetting.usableHosts',
      'subnetting.jumpSize',
    ],
  },
  {
    id: 'subnetting.firstHost',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'classic-method',
    conceptCluster: 'subnetting.calculation',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'Berechne die erste nutzbare Hostadresse aus IP und Präfix.',
      calculationFamily: 'subnetting',
      target: 'firstHost',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26, allowOctetChange: false, privateOnly: true },
        medium: { prefixMin: 16, prefixMax: 30, allowOctetChange: true, privateOnly: true },
        hard: { prefixMin: 8, prefixMax: 30, allowOctetChange: true, privateOnly: true },
      },
      distractorStrategy: 'subnettingFirstHost',
    },
    siblings: [
      'subnetting.networkId',
      'subnetting.broadcast',
      'subnetting.lastHost',
      'subnetting.usableHosts',
      'subnetting.jumpSize',
    ],
  },
  {
    id: 'subnetting.lastHost',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'classic-method',
    conceptCluster: 'subnetting.calculation',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'Berechne die letzte nutzbare Hostadresse aus IP und Präfix.',
      calculationFamily: 'subnetting',
      target: 'lastHost',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26, allowOctetChange: false, privateOnly: true },
        medium: { prefixMin: 16, prefixMax: 30, allowOctetChange: true, privateOnly: true },
        hard: { prefixMin: 8, prefixMax: 30, allowOctetChange: true, privateOnly: true },
      },
      distractorStrategy: 'subnettingLastHost',
    },
    siblings: [
      'subnetting.networkId',
      'subnetting.broadcast',
      'subnetting.firstHost',
      'subnetting.usableHosts',
      'subnetting.jumpSize',
    ],
  },
  {
    id: 'subnetting.usableHosts',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'classic-method',
    conceptCluster: 'subnetting.calculation',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'Berechne die Anzahl nutzbarer Hostadressen aus dem Präfix.',
      calculationFamily: 'subnetting',
      target: 'usableHosts',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26, allowOctetChange: false, privateOnly: true },
        medium: { prefixMin: 16, prefixMax: 30, allowOctetChange: true, privateOnly: true },
        hard: { prefixMin: 8, prefixMax: 30, allowOctetChange: true, privateOnly: true },
      },
      distractorStrategy: 'subnettingUsableHosts',
    },
    siblings: [
      'subnetting.networkId',
      'subnetting.broadcast',
      'subnetting.firstHost',
      'subnetting.lastHost',
      'subnetting.jumpSize',
    ],
  },
  {
    id: 'subnetting.jumpSize',
    topicKey: SUBNETTING_TOPIC_KEY,
    sourceTopicKey: SUBNETTING_TOPIC_KEY,
    sourceSection: 'intuitive-jump-table',
    conceptCluster: 'subnetting.calculation',
    type: KNOWLEDGE_TYPES.CALCULATION,
    difficulty: DIFFICULTY.MEDIUM,
    allowedQuestionTypes: [QUESTION_ARCHETYPES.CALCULATION, QUESTION_ARCHETYPES.INPUT, QUESTION_ARCHETYPES.SELECT_BEST, QUESTION_ARCHETYPES.SCENARIO],
    data: {
      description: 'Berechne die Sprungweite im relevanten Oktett aus dem Präfix.',
      calculationFamily: 'subnetting',
      target: 'jumpSize',
      difficultyRanges: {
        easy: { prefixMin: 24, prefixMax: 26, allowOctetChange: false, privateOnly: true },
        medium: { prefixMin: 16, prefixMax: 30, allowOctetChange: true, privateOnly: true },
        hard: { prefixMin: 8, prefixMax: 30, allowOctetChange: true, privateOnly: true },
      },
      distractorStrategy: 'subnettingJumpSize',
    },
    siblings: [
      'subnetting.networkId',
      'subnetting.broadcast',
      'subnetting.firstHost',
      'subnetting.lastHost',
      'subnetting.usableHosts',
    ],
  },
];
